K.map.sentences = {
    'Chapter 18. package managers': [
        {'en': 'Chapter', 'pumsa': 'NN', 'ko': ''},
        {'en': '18.', 'pumsa': 'CD', 'ko': ''},
        {'en': 'package managers', 'pumsa': 'NNS', 'ko': ''},
    ],

    '“Every programmer is an author.”': [
        {'en': '“', 'pumsa': 'NN', 'ko': ''},
        {'en': 'Every', 'pumsa': 'DT', 'ko': ''},
        {'en': 'programmer', 'pumsa': 'NN', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'an', 'pumsa': 'DT', 'ko': ''},
        {'en': 'author', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
        {'en': '”', 'pumsa': 'NN', 'ko': ''},
    ],

    '― Sercan Leylek': [
        {'en': '―', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'Sercan', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'Leylek', 'pumsa': 'NNP', 'ko': ''},
    ],

    'A <b>package manager</b> is a program that installs and manages other programs.': [
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'installs', 'pumsa': 'VB', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'manages', 'pumsa': 'VB', 'ko': ''},
        {'en': 'other', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'programs', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'They are useful because you often need to use other programs to create new software.': [
        {'en': 'They', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'are', 'pumsa': 'VB', 'ko': ''},
        {'en': 'useful', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'because', 'pumsa': 'IN', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'often', 'pumsa': 'RB', 'ko': ''},
        {'en': 'need to', 'pumsa': 'MD', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'other', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'programs', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'create', 'pumsa': 'VB', 'ko': ''},
        {'en': 'new', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'software', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'For example, web developers often use a <b>web framework</b>: a program that helps you build a website.': [
        {'en': 'For example', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'web', 'pumsa': 'NN', 'ko': ''},
        {'en': 'developers', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'often', 'pumsa': 'RB', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'web', 'pumsa': 'NN', 'ko': ''},
        {'en': 'framework', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'helps', 'pumsa': 'VB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'build', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'website', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Programmers use package managers to install web frameworks, as well as a variety of other programs.': [
        {'en': 'Programmers', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'package managers', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'install', 'pumsa': 'VB', 'ko': ''},
        {'en': 'web', 'pumsa': 'NN', 'ko': ''},
        {'en': 'frameworks', 'pumsa': 'NNS', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'as', 'pumsa': 'RB', 'ko': ''},
        {'en': 'well', 'pumsa': 'RB', 'ko': ''},
        {'en': 'as', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'variety', 'pumsa': 'NN', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'other', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'programs', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'In this chapter, you will learn to use the package manager <b>pip</b>.': [
        {'en': 'In this chapter', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'will', 'pumsa': 'MD', 'ko': ''},
        {'en': 'learn', 'pumsa': 'VB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Packages': [
        {'en': 'Packages', 'pumsa': 'NNS', 'ko': ''},
    ],

    'A <b>package</b> is software “packaged” for distribution - it includes the files that make up the actual program, as well as <b>metadata</b>: data about data like the software’s name, version number, and <b>dependencies</b>: the programs a program relies on to run properly.': [
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'software', 'pumsa': 'NN', 'ko': ''},
        {'en': '“', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packaged', 'pumsa': 'VB', 'ko': ''},
        {'en': '”', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'distribution', 'pumsa': 'NN', 'ko': ''},
        {'en': '-', 'pumsa': ':', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'includes', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'files', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'make', 'pumsa': 'VB', 'ko': ''},
        {'en': 'up', 'pumsa': 'RP', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'actual', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'as', 'pumsa': 'RB', 'ko': ''},
        {'en': 'well', 'pumsa': 'RB', 'ko': ''},
        {'en': 'as', 'pumsa': 'IN', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'metadata', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'data', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'about', 'pumsa': 'IN', 'ko': ''},
        {'en': 'data', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'like', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'software', 'pumsa': 'NN', 'ko': ''},
        {'en': '’s', 'pumsa': 'POS', 'ko': ''},
        {'en': 'name', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'version number', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'dependencies', 'pumsa': 'NNS', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'programs', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'relies', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'run', 'pumsa': 'VB', 'ko': ''},
        {'en': 'properly', 'pumsa': 'RB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'You can use a package manager to download a package and install it as a program on your computer.': [
        {'en': 'You', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'install', 'pumsa': 'VB', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'as', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'computer', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'The package manager handles downloading any dependencies the package has.': [
        {'en': 'The', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': 'handles', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'downloading', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'any', 'pumsa': 'DT', 'ko': ''},
        {'en': 'dependencies', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'has', 'pumsa': 'VB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Pip': [
        {'en': 'Pip', 'pumsa': 'NN', 'ko': ''},
    ],

    'In this section, I will show you how to use pip, a package manager for Python, to download Python packages.': [
        {'en': 'In', 'pumsa': 'IN', 'ko': ''},
        {'en': 'this', 'pumsa': 'DT', 'ko': ''},
        {'en': 'section', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'I', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'will', 'pumsa': 'MD', 'ko': ''},
        {'en': 'show', 'pumsa': 'VB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'how', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Once you’ve downloaded a package with pip, you can import it as a module in a Python program.': [
        {'en': 'Once', 'pumsa': 'RB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': '’', 'pumsa': 'VB', 'ko': ''},
        {'en': 've', 'pumsa': 'RB', 'ko': ''},
        {'en': 'downloaded', 'pumsa': 'VBN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'import', 'pumsa': 'VB', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'as', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'module', 'pumsa': 'NN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'First, check to see if pip is installed on your computer by opening Bash, or the Command Prompt if you are using Windows, and entering the command <code>pip</code>:': [
        {'en': 'First', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'check', 'pumsa': 'VB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'see', 'pumsa': 'VB', 'ko': ''},
        {'en': 'if', 'pumsa': 'IN', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'installed', 'pumsa': 'VBN', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'computer', 'pumsa': 'NN', 'ko': ''},
        {'en': 'by', 'pumsa': 'IN', 'ko': ''},
        {'en': 'opening', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'Bash', 'pumsa': 'NNP', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'or', 'pumsa': 'CC', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Command Prompt', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'if', 'pumsa': 'IN', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'are', 'pumsa': 'VB', 'ko': ''},
        {'en': 'using', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'Windows', 'pumsa': 'NNP', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'entering', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command', 'pumsa': 'NNP', 'ko': ''},
        {'en': '<code>pip</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
    ],

    'When you enter the command, a list of options should print.': [
        {'en': 'When', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'enter', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'list', 'pumsa': 'NN', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'options', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'should', 'pumsa': 'MD', 'ko': ''},
        {'en': 'print', 'pumsa': 'VB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Pip comes with Python when you download it, but it didn’t in earlier versions.': [
        {'en': 'Pip', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'comes', 'pumsa': 'VB', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'when', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'but', 'pumsa': 'CC', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'didn', 'pumsa': 'VB', 'ko': ''},
        {'en': '’', 'pumsa': 'JJ', 'ko': ''},
        {'en': 't', 'pumsa': 'NN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'earlier versions', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'If nothing happens when you enter the <code>pip</code> command, pip is not installed on your computer.': [
        {'en': 'If', 'pumsa': 'IN', 'ko': ''},
        {'en': 'nothing', 'pumsa': 'NN', 'ko': ''},
        {'en': 'happens', 'pumsa': 'VB', 'ko': ''},
        {'en': 'when', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'enter', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': '<code>pip</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': 'command', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'not', 'pumsa': 'RB', 'ko': ''},
        {'en': 'installed', 'pumsa': 'VBN', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'computer', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Visit <URL>http://www.theselftaughtprogrammerio/pip</URL> for instructions on installing it.': [
        {'en': 'Visit', 'pumsa': 'NNP', 'ko': ''},
        {'en': '<URL>http://www.theselftaughtprogrammerio/pip</URL>', 'pumsa': 'URL', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'instructions', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'installing', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'You can install a new package with <code>pip install [package_name]</code>.': [
        {'en': 'You', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'install', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'new', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': '<code>pip install [package_name]</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Pip installs new packages into a folder in your Python directory called <code>site-packages</code>.': [
        {'en': 'Pip', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'installs', 'pumsa': 'VB', 'ko': ''},
        {'en': 'new', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'into', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'folder', 'pumsa': 'NN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'directory', 'pumsa': 'NN', 'ko': ''},
        {'en': 'called', 'pumsa': 'VBN', 'ko': ''},
        {'en': '<code>site-packages</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'You can find a list of all the Python packages available for download at <URL>https://pypi.python.org/pypi</URL>.': [
        {'en': 'You', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'find', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'list', 'pumsa': 'NN', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'all', 'pumsa': 'PDT', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'available', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'download', 'pumsa': 'NN', 'ko': ''},
        {'en': 'at', 'pumsa': 'IN', 'ko': ''},
        {'en': '<URL>https://pypi.python.org/pypi</URL>', 'pumsa': 'URL', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'There are two ways to specify the package you want to download - the package name, or the package name followed by two equal signs ( <code>==</code>) and the version number you want to download.': [
        {'en': 'There', 'pumsa': 'EX', 'ko': ''},
        {'en': 'are', 'pumsa': 'VB', 'ko': ''},
        {'en': 'two', 'pumsa': 'CD', 'ko': ''},
        {'en': 'ways', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'specify', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'want', 'pumsa': 'VB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': '-', 'pumsa': ':', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'name', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'or', 'pumsa': 'CC', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'name', 'pumsa': 'NN', 'ko': ''},
        {'en': 'followed', 'pumsa': 'VBN', 'ko': ''},
        {'en': 'by', 'pumsa': 'IN', 'ko': ''},
        {'en': 'two', 'pumsa': 'CD', 'ko': ''},
        {'en': 'equal signs', 'pumsa': 'NNS', 'ko': ''},
        {'en': '(', 'pumsa': '(', 'ko': ''},
        {'en': '<code>==</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': ')', 'pumsa': ')', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'version number', 'pumsa': 'NN', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'want', 'pumsa': 'VB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'If you use the package name, pip will download the most recent version of the package.': [
        {'en': 'If', 'pumsa': 'IN', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'name', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': 'will', 'pumsa': 'MD', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'most', 'pumsa': 'RB', 'ko': ''},
        {'en': 'recent', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'version', 'pumsa': 'NN', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'The second option allows you to download a particular package version, instead of the most current.': [
        {'en': 'The', 'pumsa': 'DT', 'ko': ''},
        {'en': 'second', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'option', 'pumsa': 'NN', 'ko': ''},
        {'en': 'allows', 'pumsa': 'VB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'particular', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'version', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'instead', 'pumsa': 'RB', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'most', 'pumsa': 'RB', 'ko': ''},
        {'en': 'current', 'pumsa': 'JJ', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Here is how to install <code>Flask</code>, a Python package for creating websites on Ubuntu and Unix:': [
        {'en': 'Here', 'pumsa': 'RB', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'how', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'install', 'pumsa': 'VB', 'ko': ''},
        {'en': '<code>Flask</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'creating', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'websites', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'Ubuntu', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'Unix', 'pumsa': 'NNP', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
    ],

    'On Windows, you need to use the command-line as an administrator.': [
        {'en': 'On', 'pumsa': 'IN', 'ko': ''},
        {'en': 'Windows', 'pumsa': 'NNP', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'need to', 'pumsa': 'MD', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command-line', 'pumsa': 'NN', 'ko': ''},
        {'en': 'as', 'pumsa': 'IN', 'ko': ''},
        {'en': 'an', 'pumsa': 'DT', 'ko': ''},
        {'en': 'administrator', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Right-click on the command-prompt icon and select <code>Run as administrator</code>.': [
        {'en': 'Right-click', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command-prompt', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'icon', 'pumsa': 'NN', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'select', 'pumsa': 'JJ', 'ko': ''},
        {'en': '<code>Run as administrator</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Inside the Command Prompt enter:': [
        {'en': 'Inside', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Command Prompt', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'enter', 'pumsa': 'NN', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
    ],

    'With this command, pip installs the <code>Flask</code> module in your computer’s <code>site-packages</code> folder.': [
        {'en': 'With', 'pumsa': 'IN', 'ko': ''},
        {'en': 'this', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': 'installs', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': '<code>Flask</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': 'module', 'pumsa': 'NN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'computer', 'pumsa': 'NN', 'ko': ''},
        {'en': '’s', 'pumsa': 'POS', 'ko': ''},
        {'en': '<code>site-packages</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': 'folder', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Now, you can import the <code>Flask</code> module in a program.': [
        {'en': 'Now', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'import', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': '<code>Flask</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': 'module', 'pumsa': 'NN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Create a new Python file, add the following code, and run the program:': [
        {'en': 'Create', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'new', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'file', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'add', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'following', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'code', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'run', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
    ],

    'Now, navigate to <URL>http://127.0.0.1:8000/</URL> in your web browser, and you should see a website that says <code>Hello, World!</code>': [
        {'en': 'Now', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'navigate', 'pumsa': 'NN', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': '<URL>http://127.0.0.1:8000/</URL>', 'pumsa': 'URL', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'web', 'pumsa': 'NN', 'ko': ''},
        {'en': 'browser', 'pumsa': 'NN', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'should', 'pumsa': 'MD', 'ko': ''},
        {'en': 'see', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'website', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'says', 'pumsa': 'VB', 'ko': ''},
        {'en': '<code>Hello, World!</code>', 'pumsa': 'CODE', 'ko': ''},
    ],

    '../Images/flask.png': [
        {'en': '../Images/flask.png', 'pumsa': 'NN', 'ko': ''},
    ],

    'The <code> Flask</code> module allows you to create a web server and a website quickly.': [
        {'en': 'The', 'pumsa': 'DT', 'ko': ''},
        {'en': '<code> Flask</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': 'module', 'pumsa': 'NN', 'ko': ''},
        {'en': 'allows', 'pumsa': 'VB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'create', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'web', 'pumsa': 'NN', 'ko': ''},
        {'en': 'server', 'pumsa': 'NN', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'website', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'quickly', 'pumsa': 'RB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Visit <URL>http://flask.pocoo.org/docs/0.11/tutorial</URL> to learn more about how this example works.': [
        {'en': 'Visit', 'pumsa': 'NNP', 'ko': ''},
        {'en': '<URL>http://flask.pocoo.org/docs/0.11/tutorial</URL>', 'pumsa': 'URL', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'learn', 'pumsa': 'VB', 'ko': ''},
        {'en': 'more', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'about', 'pumsa': 'IN', 'ko': ''},
        {'en': 'how', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'this', 'pumsa': 'DT', 'ko': ''},
        {'en': 'example', 'pumsa': 'NN', 'ko': ''},
        {'en': 'works', 'pumsa': 'VB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'You can view the packages you’ve installed with the command <code>pip freeze</code>:': [
        {'en': 'You', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'view', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': '’', 'pumsa': 'VB', 'ko': ''},
        {'en': 've', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'installed', 'pumsa': 'VBN', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command', 'pumsa': 'NN', 'ko': ''},
        {'en': '<code>pip freeze</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
    ],

    'Finally, you can uninstall a program with <code>pip uninstall [package_name]</code>.': [
        {'en': 'Finally', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'uninstall', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': '<code>pip uninstall [package_name]</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Uninstall Flask with the following command:': [
        {'en': 'Uninstall', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Flask', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'following', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'command', 'pumsa': 'NN', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
    ],

    'Flask is now uninstalled, which you can verify with the command <code>pip freeze</code>.': [
        {'en': 'Flask', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'now', 'pumsa': 'RB', 'ko': ''},
        {'en': 'uninstalled', 'pumsa': 'JJ', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'which', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'verify', 'pumsa': 'VB', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'command', 'pumsa': 'NN', 'ko': ''},
        {'en': '<code>pip freeze</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Virtual environments': [
        {'en': 'Virtual', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'environments', 'pumsa': 'NNS', 'ko': ''},
    ],

    'Eventually, you will want to install your Python packages into a <b>virtual environment</b> instead of installing all of your packages into <code>site-packages</code>.': [
        {'en': 'Eventually', 'pumsa': 'RB', 'ko': ''},
        {'en': ',', 'pumsa': ',', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'will', 'pumsa': 'MD', 'ko': ''},
        {'en': 'want', 'pumsa': 'VB', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'install', 'pumsa': 'VB', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packages', 'pumsa': 'VB', 'ko': ''},
        {'en': 'into', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'virtual', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'environment', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'instead', 'pumsa': 'RB', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'installing', 'pumsa': 'VBG', 'ko': ''},
        {'en': 'all', 'pumsa': 'DT', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'into', 'pumsa': 'IN', 'ko': ''},
        {'en': '<code>site-packages</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Virtual environments allow you to keep the Python packages for your different programming projects separate.': [
        {'en': 'Virtual', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'environments', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'allow', 'pumsa': 'VB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'keep', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'different', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'programming', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'projects', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'separate', 'pumsa': 'VB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'You can learn more about virtual environments at <URL>http://docs.python-guide.org/en/latest/dev/virtualenvs</URL>.': [
        {'en': 'You', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'can', 'pumsa': 'MD', 'ko': ''},
        {'en': 'learn', 'pumsa': 'VB', 'ko': ''},
        {'en': 'more', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'about', 'pumsa': 'IN', 'ko': ''},
        {'en': 'virtual', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'environments', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'at', 'pumsa': 'IN', 'ko': ''},
        {'en': '<URL>http://docs.python-guide.org/en/latest/dev/virtualenvs</URL>', 'pumsa': 'URL', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Vocabulary': [
        {'en': 'Vocabulary', 'pumsa': 'NNP', 'ko': ''},
    ],

    '<b>Package manager</b>: A program that installs and manages other programs.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'installs', 'pumsa': 'VB', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'manages', 'pumsa': 'VB', 'ko': ''},
        {'en': 'other', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'programs', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Web framework</b>: A program that helps you build a website.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Web', 'pumsa': 'NN', 'ko': ''},
        {'en': 'framework', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'helps', 'pumsa': 'VB', 'ko': ''},
        {'en': 'you', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'build', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'website', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Package</b>: Software “packaged” for distribution.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Package', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'Software', 'pumsa': 'NNP', 'ko': ''},
        {'en': '“', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packaged', 'pumsa': 'VB', 'ko': ''},
        {'en': '”', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'distribution', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Metadata</b>: Data about data.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Metadata', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'Data', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'about', 'pumsa': 'IN', 'ko': ''},
        {'en': 'data', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Dependencies</b>: The programs a program relies on to run properly.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Dependencies', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'The', 'pumsa': 'DT', 'ko': ''},
        {'en': 'programs', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'program', 'pumsa': 'NN', 'ko': ''},
        {'en': 'relies', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'run', 'pumsa': 'VB', 'ko': ''},
        {'en': 'properly', 'pumsa': 'RB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Apt-get</b>: A package manager that comes with Ubuntu.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Apt-get', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'comes', 'pumsa': 'VB', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'Ubuntu', 'pumsa': 'NNP', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Pip</b>: A package manager for Python.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Pip', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'manager', 'pumsa': 'NN', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>$PYTHONPATH</b>: Python looks for modules in a list of folders stored in an environmental variable called <code>$PYTHONPATH</code>.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': '$', 'pumsa': '$', 'ko': ''},
        {'en': 'PYTHONPATH', 'pumsa': 'NNP', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'looks', 'pumsa': 'VB', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'modules', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'list', 'pumsa': 'NN', 'ko': ''},
        {'en': 'of', 'pumsa': 'IN', 'ko': ''},
        {'en': 'folders', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'stored', 'pumsa': 'VBN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': 'an', 'pumsa': 'DT', 'ko': ''},
        {'en': 'environmental variable', 'pumsa': 'NN', 'ko': ''},
        {'en': 'called', 'pumsa': 'VBN', 'ko': ''},
        {'en': '<code>$PYTHONPATH</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Site-packages</b>: A folder in <code>$PYTHONPATH</code>.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Site-packages', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': 'folder', 'pumsa': 'NN', 'ko': ''},
        {'en': 'in', 'pumsa': 'IN', 'ko': ''},
        {'en': '<code>$PYTHONPATH</code>', 'pumsa': 'CODE', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'This folder is where pip installs packages.': [
        {'en': 'This', 'pumsa': 'DT', 'ko': ''},
        {'en': 'folder', 'pumsa': 'NN', 'ko': ''},
        {'en': 'is', 'pumsa': 'VB', 'ko': ''},
        {'en': 'where', 'pumsa': 'WRB', 'ko': ''},
        {'en': 'pip', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'installs', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>PyPI</b>: A website that hosts Python packages.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'PyPI', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'A', 'pumsa': 'DT', 'ko': ''},
        {'en': 'website', 'pumsa': 'NN', 'ko': ''},
        {'en': 'that', 'pumsa': 'WDT', 'ko': ''},
        {'en': 'hosts', 'pumsa': 'VB', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<b>Virtual environment</b>: You use a virtual environment to keep the Python packages for your different programming projects separate.': [
        {'en': '<b>', 'pumsa': 'B', 'ko': ''},
        {'en': 'Virtual', 'pumsa': 'NN', 'ko': ''},
        {'en': 'environment', 'pumsa': 'NN', 'ko': ''},
        {'en': '</b>', 'pumsa': 'B', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': 'You', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'use', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'virtual', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'environment', 'pumsa': 'NN', 'ko': ''},
        {'en': 'to', 'pumsa': 'TO', 'ko': ''},
        {'en': 'keep', 'pumsa': 'VB', 'ko': ''},
        {'en': 'the', 'pumsa': 'DT', 'ko': ''},
        {'en': 'Python', 'pumsa': 'NNP', 'ko': ''},
        {'en': 'packages', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'for', 'pumsa': 'IN', 'ko': ''},
        {'en': 'your', 'pumsa': 'PRP$', 'ko': ''},
        {'en': 'different', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'programming', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'projects', 'pumsa': 'NNS', 'ko': ''},
        {'en': 'separate', 'pumsa': 'VB', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    '<h2>': [
        {'en': '<', 'pumsa': 'JJ', 'ko': ''},
        {'en': 'h2', 'pumsa': 'NN', 'ko': ''},
        {'en': '>', 'pumsa': 'NN', 'ko': ''},
    ],

    'Challenge': [
        {'en': 'Challenge', 'pumsa': 'NN', 'ko': ''},
    ],

    '1. Find a package on PyPI (<URL>https://pypi.python.org</URL>) and download it with pip.': [
        {'en': '1', 'pumsa': 'CD', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
        {'en': 'Find', 'pumsa': 'VB', 'ko': ''},
        {'en': 'a', 'pumsa': 'DT', 'ko': ''},
        {'en': 'package', 'pumsa': 'NN', 'ko': ''},
        {'en': 'on', 'pumsa': 'IN', 'ko': ''},
        {'en': 'PyPI', 'pumsa': 'NNP', 'ko': ''},
        {'en': '(', 'pumsa': '(', 'ko': ''},
        {'en': '<URL>https://pypi.python.org</URL>', 'pumsa': 'URL', 'ko': ''},
        {'en': ')', 'pumsa': ')', 'ko': ''},
        {'en': 'and', 'pumsa': 'CC', 'ko': ''},
        {'en': 'download', 'pumsa': 'VB', 'ko': ''},
        {'en': 'it', 'pumsa': 'PRP', 'ko': ''},
        {'en': 'with', 'pumsa': 'IN', 'ko': ''},
        {'en': 'pip', 'pumsa': 'NN', 'ko': ''},
        {'en': '.', 'pumsa': '.', 'ko': ''},
    ],

    'Solution: <URL>http://tinyurl.com/h96qbw2.</URL>': [
        {'en': 'Solution', 'pumsa': 'NN', 'ko': ''},
        {'en': ':', 'pumsa': ':', 'ko': ''},
        {'en': '<URL>http://tinyurl.com/h96qbw2.</URL>', 'pumsa': 'URL', 'ko': ''},
    ],
}