K.array.word = [
{en:'four pillars of object-oriented programming', ko:'객체 지향 프로그래밍의 네 가지 기둥', pumsa:'NN'},
{en:'leading and trailing whitespace', ko:'앞뒤 공백', pumsa:'NN'},
{en:'Jan L. A. van de Snepscheut', ko:'요하네스 L. A. 판더스넵스회트', pumsa:'NNP'},
{en:'Python programming language', ko:'파이썬', pumsa:'NNP'},
{en:'Unix-like operating systems', ko:'유닉스 계열 운영체제', pumsa:'NNS'},
{en:'object-oriented programming', ko:'객체 지향 프로그래밍', pumsa:'NN'},
{en:'best programming practices', ko:'프로그래밍 모범 사례', pumsa:'NNS'},
{en:'bringing it all together', ko:'하나로 모아서', pumsa:'Clause'},
{en:'greatest common divisor', ko:'최대공약수', pumsa:'NN'},
{en:'trigonometric functions', ko:'삼각함수', pumsa:'NNS'},
{en:'will raise an exception', ko:'예외를 일으', pumsa:'VBNN'},
{en:'instantiation operation', ko:'인스턴스화', pumsa:'NN'},
{en:'multiplication operator', ko:'곱셈 연산자', pumsa:'NN'},
{en:'version control systems', ko:'버전 컨트롤 시스템', pumsa:'NNS'},
{en:'environmental variables', ko:'환경 변수', pumsa:'NNS'},
{en:'environmental variable', ko:'환경 변수', pumsa:'NN'},
{en:'functional programming', ko:'함수형 프로그래밍', pumsa:'NN'},
{en:'command-line interface', ko:'명령행 인터페이스', pumsa:'NN'},
{en:'geographic coordinates', ko:'위도와 경도', pumsa:'NNS'},
{en:'trigonometric function', ko:'삼각함수', pumsa:'NN'},
{en:'floating point numbers', ko:'부동소수점 숫자', pumsa:'NNS'},
{en:'representational forms', ko:'내부적 형태', pumsa:'NNS'},
{en:'representational form', ko:'내부적 형태', pumsa:'NN'},
{en:'floating point number', ko:'부동소수점 숫자', pumsa:'NN'},
{en:'logarithmic functions', ko:'로그 함수', pumsa:'NNS'},
{en:'programming community', ko:'프로그래밍 커뮤니티', pumsa:'NN'},
{en:'programming languages', ko:'프로그래밍 언어', pumsa:'NNS'},
{en:'floating-point number', ko:'부동소수점 숫자', pumsa:'NN'},
{en:'floating-point object', ko:'부동소수점 숫자 객체', pumsa:'NN'},
{en:'programming paradigms', ko:'프로그래밍 패러다임', pumsa:'NNS'},
{en:'operating system user', ko:'운영체제 사용자', pumsa:'NN'},
{en:'programming paradigm', ko:'프로그래밍 패러다임', pumsa:'NN'},
{en:'computer programming', ko:'컴퓨터 프로그래밍', pumsa:'NN'},
{en:'programming language', ko:'프로그래밍 언어', pumsa:'NN'},
{en:'logarithmic function', ko:'로그 함수', pumsa:'NN'},
{en:'floating point value', ko:'부동소수점 숫자', pumsa:'NN'},
{en:'ordered dictionaries', ko:'순서 있는 딕셔너리', pumsa:'NNS'},
{en:'list comprehensions', ko:'리스트 내포', pumsa:'NNS'},
{en:'separated by commas', ko:'콤마로 구분', pumsa:'JJ'},
{en:'separated by commas', ko:'콤마로 구분된', pumsa:'JJ_noun'},
{en:'required parameters', ko:'필수 매개변수', pumsa:'NNS'},
{en:'fibonacci sequences', ko:'피보나치 수열', pumsa:'NNS'},
{en:'as an administrator', ko:'관리자 권한으로', pumsa:'RB_Clause'},
{en:'string manipulation', ko:'문자열 조작', pumsa:'NN'},
{en:'compound statements', ko:'복합문', pumsa:'NNS'},
{en:'regular expressions', ko:'정규 표현식', pumsa:'NNS'},
{en:'raises an exception', ko:'예외를 일으', pumsa:'VBNN'},
{en:'closely associated', ko:'밀접하게 연관', pumsa:'JJ'},
{en:'closely associated', ko:'밀접하게 연관된', pumsa:'JJ_noun'},
{en:'exception handling', ko:'예외 처리', pumsa:'NN'},
{en:'compound statement', ko:'복합문', pumsa:'NN'},
{en:'instance variables', ko:'인스턴스 변수', pumsa:'NNS'},
{en:'naming conventions', ko:'이름 규칙', pumsa:'NNS'},
{en:'client programmers', ko:'클라이언트 프로그래머', pumsa:'NNS'},
{en:'fibonacci sequence', ko:'피보나치 수열', pumsa:'NN'},
{en:'special characters', ko:'특수 문자', pumsa:'NN'},
{en:'from the beginning', ko:'처음부터', pumsa:'RB'},
{en:'significant digits', ko:'유효숫자', pumsa:'NN'},
{en:'from right to left', ko:'오른쪽에서 왼쪽으로', pumsa:'RB'},
{en:'previously defined', ko:'이미 정의된', pumsa:'JJ_noun'},
{en:'required parameter', ko:'필수 매개변수', pumsa:'NN'},
{en:'optional parameter', ko:'옵션 매개변수', pumsa:'NN'},
{en:'list comprehension', ko:'리스트 내포', pumsa:'NN'},
{en:'bitwise operations', ko:'비트 연산', pumsa:'NNS'},
{en:'membership testing', ko:'멤버 테스트', pumsa:'NN'},
{en:'multiple different', ko:'여러 가지', pumsa:'JJ'},
{en:'regular expression', ko:'정규 표현식', pumsa:'NN'},
{en:'central repository', ko:'원격 저장소', pumsa:'NN'},
{en:'zero or more times', ko:'0 번 이상', pumsa:'RB'},
{en:'working directory', ko:'작업 디렉토리', pumsa:'NN'},
{en:'instance variable', ko:'인스턴스 변수', pumsa:'NN'},
{en:'bitwise operation', ko:'비트 연산', pumsa:'NN'},
{en:'associative array', ko:'연관 배열', pumsa:'NN'},
{en:'complex data type', ko:'복소수 데이터 타입', pumsa:'NN'},
{en:'activation record', ko:'활성 레코드', pumsa:'NN'},
{en:'garbage-collected', ko:'가비지 컬렉션', pumsa:'JJ'},
{en:'operating systems', ko:'운영체제', pumsa:'NNS'},
{en:'Python’s built-in', ko:'파이썬에 내장된', pumsa:'JJ_noun'},
{en:'multi-dimensional', ko:'다차원', pumsa:'JJ'},
{en:'special character', ko:'특수 문자', pumsa:'NN'},
{en:'private variables', ko:'프라이빗 변수', pumsa:'NNS'},
{en:'method overriding', ko:'메서드 오버라이딩', pumsa:'VBG'},
{en:'counterproductive', ko:'비효율적', pumsa:'JJ'},
{en:'counterproductive', ko:'비효율적', pumsa:'JJ_noun'},
{en:'addition operator', ko:'덧셈 연산자', pumsa:'NN'},
{en:'dictionary value', ko:'딕셔너리 값', pumsa:'NN'},
{en:'from here on out', ko:'지금부터는', pumsa:'RB'},
{en:'computer science', ko:'컴퓨터 공학', pumsa:'NN'},
{en:'acknowledgements', ko:'감사의 글', pumsa:'NNS'},
{en:'built-in modules', ko:'내장 모듈', pumsa:'NNS'},
{en:'operating system', ko:'운영체제', pumsa:'NN'},
{en:'package managers', ko:'패키지 매니저', pumsa:'NNS'},
{en:'public variables', ko:'공용 변수', pumsa:'VB'},
{en:'simple statement', ko:'단순문', pumsa:'NN'},
{en:'line terminators', ko:'줄 끝 문자', pumsa:'NNS'},
{en:'single precision', ko:'단정도', pumsa:'NN'},
{en:'reverse engineer', ko:'디컴파일', pumsa:'VB'},
{en:'high-performance', ko:'고성능', pumsa:'NN'},
{en:'class definition', ko:'클래스 정의', pumsa:'NN'},
{en:'local repository', ko:'로컬 저장소', pumsa:'NN'},
{en:'earlier versions', ko:'이전 버전', pumsa:'NNS'},
{en:'make changes to', ko:'변경', pumsa:'VB'},
{en:'object-oriented', ko:'객체 지향이나', pumsa:'JJ_or'},
{en:'global variable', ko:'전역 변수', pumsa:'NN'},
{en:'object-oriented', ko:'객체 지향과', pumsa:'JJ_and'},
{en:'object-oriented', ko:'객체 지향', pumsa:'JJ'},
{en:'object-oriented', ko:'객체 지향', pumsa:'JJ_noun'},
{en:'forward slashes', ko:'슬래시', pumsa:'NNS'},
{en:'string of words', ko:'문자열', pumsa:'NN'},
{en:'general purpose', ko:'범용', pumsa:'JJ'},
{en:'fractional part', ko:'소수 부분', pumsa:'NN'},
{en:'complex numbers', ko:'복소수', pumsa:'NNS'},
{en:'key/value pairs', ko:'키-값 쌍', pumsa:'NNS'},
{en:'in this chapter', ko:'이 장에서는', pumsa:'RB'},
{en:'biased notation', ko:'바이어스 표기법', pumsa:'NN'},
{en:'comma-separated', ko:'콤마로 구분된', pumsa:'JJ'},
{en:'square brackets', ko:'대괄호', pumsa:'NNS'},
{en:'line terminator', ko:'줄 끝 문자', pumsa:'NN'},
{en:'a hundred times', ko:'백 번', pumsa:'RB'},
{en:'base-conversion', ko:'기수 변환', pumsa:'NN'},
{en:'two dimensional', ko:'2차원', pumsa:'JJ'},
{en:'representations', ko:'표현', pumsa:'NNS'},
{en:'lambda calculus', ko:'람다 대수', pumsa:'NN'},
{en:'present present', ko:'부여', pumsa:'VB'},
{en:'private methods', ko:'프라이빗 메서드', pumsa:'NNS'},
{en:'class variables', ko:'클래스 변수', pumsa:'NNS'},
{en:'negative number', ko:'음수', pumsa:'NN'},
{en:'getting started', ko:'시작하기', pumsa:'NN'},
{en:'Object-Oriented', ko:'객체 지향', pumsa:'NNP'},
{en:'capital letters', ko:'대문자', pumsa:'NNS'},
{en:'version control', ko:'버전 컨트롤', pumsa:'NN'},
{en:'key-value pairs', ko:'키-값 쌍', pumsa:'NNS'},
{en:'characteristics', ko:'특징', pumsa:'NNS'},
{en:'for this reason', ko:'따라서', pumsa:'RB'},
{en:'design patterns', ko:'디자인 패턴', pumsa:'NNS'},
{en:'many different', ko:'여러 가지', pumsa:'JJ'},
{en:'transformation', ko:'변형', pumsa:'NN'},
{en:'in other words', ko:'달리 말해', pumsa:'RB'},
{en:'conventionally', ko:'보통', pumsa:'RB'},
{en:'key-value pair', ko:'키-값 쌍', pumsa:'NN'},
{en:'dictionary key', ko:'딕셔너리 키', pumsa:'NN'},
{en:'data structure', ko:'데이터 구조', pumsa:'NN'},
{en:'negative index', ko:'음수 인덱스', pumsa:'NN'},
{en:'curly brackets', ko:'중괄호', pumsa:'NNS'},
{en:'multiplication', ko:'곱셈', pumsa:'NN'},
{en:'index variable', ko:'인덱스 변수', pumsa:'NN'},
{en:'many different', ko:'여러 가지', pumsa:'JJ_noun'},
{en:'user interface', ko:'사용자 인터페이스', pumsa:'NN'},
{en:'function names', ko:'함수 이름', pumsa:'NNS'},
{en:'capital letter', ko:'대문자', pumsa:'NN'},
{en:'left-hand side', ko:'좌변', pumsa:'NN'},
{en:'representation', ko:'표현', pumsa:'NN'},
{en:'human-readable', ko:'사람이 읽을 수 있', pumsa:'JJ'},
{en:'reconstructing', ko:'재구성', pumsa:'VBG'},
{en:'square bracket', ko:'대괄호', pumsa:'NN'},
{en:'integer object', ko:'정수 객체', pumsa:'NN'},
{en:'key/value pair', ko:'키-값 쌍', pumsa:'NN'},
{en:'complex number', ko:'복소수', pumsa:'NN'},
{en:'primes factors ', ko:'소인수', pumsa:'NNS'},
{en:'from the right', ko:'오른쪽에서', pumsa:'RB'},
{en:'multiple times', ko:'여러 번', pumsa:'RB'},
{en:'initialization', ko:'초기화', pumsa:'NN'},
{en:'search pattern', ko:'검색 패턴', pumsa:'NN'},
{en:'hyphen symbols', ko:'하이픈 기호', pumsa:'NNS'},
{en:'Command Prompt', ko:'명령 프롬프트', pumsa:'NNP'},
{en:'newest version', ko:'최신 버전', pumsa:'NN'},
{en:'professionally', ko:'전문적으로', pumsa:'RB'},
{en:'keeps track of', ko:'추적', pumsa:'VB'},
{en:'class variable', ko:'클래스 변수', pumsa:'NN'},
{en:'operand object', ko:'피연산자 객체', pumsa:'NN'},
{en:'absolute value', ko:'절댓값', pumsa:'NN'},
{en:'version number', ko:'버전 번호', pumsa:'NN'},
{en:'home directory', ko:'홈 디렉토리', pumsa:'NN'},
{en:'To get started', ko:'먼저', pumsa:'RB_Clause'},
{en:'encapsulation', ko:'캡슐화', pumsa:'NN'},
{en:'administrator', ko:'관리자', pumsa:'NN'},
{en:'user-supplied', ko:'사용자가 제공한', pumsa:'JJ_noun'},
{en:'class objects', ko:'클래스 객체', pumsa:'NNS'},
{en:'documentation', ko:'문서', pumsa:'NN'},
{en:'relative path', ko:'상대 경로', pumsa:'NN'},
{en:'absolute path', ko:'절대 경로', pumsa:'NN'},
{en:'question mark', ko:'물음표', pumsa:'NN'},
{en:'command line:', ko:'명령행', pumsa:'NN'},
{en:'incrementally', ko:'점진적으로', pumsa:'RB'},
{en:'primes factor', ko:'소인수', pumsa:'NN'},
{en:'prime factors', ko:'소인수', pumsa:'NNS'},
{en:'default value', ko:'기본값', pumsa:'NN'},
{en:'automatically', ko:'자동적으로', pumsa:'RB'},
{en:'left-shifting', ko:'왼쪽 시프트', pumsa:'JJ'},
{en:'complex value', ko:'복소수', pumsa:'NN'},
{en:'signed values', ko:'부호 붙은 값', pumsa:'NN'},
{en:'conceptualize', ko:'개념화', pumsa:'VB'},
{en:'inherits from', ko:'상속', pumsa:'VB'},
{en:'parent method', ko:'부모 클래스의 메서드', pumsa:'NN'},
{en:'magic methods', ko:'매직 메서드', pumsa:'NNS'},
{en:'infinite loop', ko:'무한 루프', pumsa:'NN'},
{en:'Google Sheets', ko:'구글 시트', pumsa:'NNP'},
{en:'grammatically', ko:'문법적으로', pumsa:'RB'},
{en:'single quotes', ko:'작은따옴표', pumsa:'NNS'},
{en:'double quotes', ko:'큰따옴표', pumsa:'NNS'},
{en:'corresponding', ko:'대응', pumsa:'JJ'},
{en:'corresponding', ko:'대응하는', pumsa:'JJ_noun'},
{en:'left to right', ko:'왼쪽에서 오른쪽으로', pumsa:'RB'},
{en:'concatenation', ko:'병합', pumsa:'NN'},
{en:'commonly used', ko:'널리 쓰이는', pumsa:'JJ_noun'},
{en:'good practice', ko:'좋은 습관', pumsa:'NN'},
{en:'commonly used', ko:'널리', pumsa:'JJ'},
{en:'individuality', ko:'독립성', pumsa:'NN'},
{en:'instantiation', ko:'인스턴스화', pumsa:'NN'},
{en:'intrinsically', ko:'본질적으로', pumsa:'RB'},
{en:'functionality', ko:'기능', pumsa:'NN'},
{en:'interactively', ko:'대화형으로', pumsa:'RB'},
{en:'variable name', ko:'변수 이름', pumsa:'NN'},
{en:'base classes', ko:'기반 클래스', pumsa:'NNS'},
{en:'relationship', ko:'관계', pumsa:'NN'},
{en:'make changes', ko:'변경', pumsa:'VB'},
{en:'Polymorphism', ko:'다형성', pumsa:'NNP'},
{en:'polymorphism', ko:'다형성', pumsa:'NN'},
{en:'benchmarking', ko:'벤치마크', pumsa:'VBG'},
{en:'accidentally', ko:'실수로', pumsa:'RB'},
{en:'command line', ko:'명령행', pumsa:'NN'},
{en:'dictionaries', ko:'딕셔너리', pumsa:'NN'},
{en:'representing', ko:'나타내는', pumsa:'VBG'},
{en:'type of data', ko:'데이터 타입', pumsa:'NN'},
{en:'greater than', ko:'보다 큰', pumsa:'JJ'},
{en:'manipulation', ko:'조작', pumsa:'NN'},
{en:'introduction', ko:'소개', pumsa:'NN'},
{en:'hidden files', ko:'히든 파일', pumsa:'NNS'},
{en:'Introduction', ko:'소개', pumsa:'NNP'},
{en:'syntax error', ko:'문법 에러', pumsa:'NN'},
{en:'instructions', ko:'명령', pumsa:'NNS'},
{en:'getting help', ko:'도움 받기', pumsa:'Clause'},
{en:'productivity', ko:'생산성', pumsa:'NN'},
{en:'indefinitely', ko:'독립적으로', pumsa:'RB'},
{en:'math-related', ko:'수학 관련', pumsa:'JJ_noun'},
{en:'command-line', ko:'명령행', pumsa:'NN'},
{en:'method names', ko:'메서드 이름', pumsa:'NNS'},
{en:'parent class', ko:'부모 클래스', pumsa:'NN'},
{en:'sequentially', ko:'연속적으로', pumsa:'RB'},
{en:'alphabetical', ko:'알파벳', pumsa:'JJ'},
{en:'dictionaries', ko:'딕셔너리', pumsa:'NNS'},
{en:'array-method', ko:'배열 메서드', pumsa:'NN'},
{en:'hexadecimals', ko:'16진수', pumsa:'NNS'},
{en:'mathematical', ko:'수학', pumsa:'JJ'},
{en:'zero or more', ko:'0개 이상의', pumsa:'JJ'},
{en:'particularly', ko:'특히', pumsa:'RB'},
{en:'greater than', ko:'보다 큰', pumsa:'JJR'},
{en:'global scope', ko:'전역 스코프', pumsa:'NN'},
{en:'if necessary', ko:'필요하다면', pumsa:'RB'},
{en:'spreadsheets', ko:'스프레드시트', pumsa:'NNS'},
{en:'vertical bar', ko:'파이프', pumsa:'NN'},
{en:'prime factor', ko:'소인수', pumsa:'NNS'},
{en:'for instance', ko:'예를 들어', pumsa:'RB'},
{en:'decimal base', ko:'10진법', pumsa:'NN'},
{en:'string forms', ko:'문자열 형태', pumsa:'NNS'},
{en:'linked lists', ko:'링크드 리스트', pumsa:'NNS'},
{en:'non-existent', ko:'존재하지 않는', pumsa:'JJ'},
{en:'control flow', ko:'흐름 제어', pumsa:'NN'},
{en:'simple match', ko:'단순 일치', pumsa:'NN'},
{en:'Bash web app', ko:'배시 웹 앱', pumsa:'NN'},
{en:'Python Shell', ko:'파이썬 셸', pumsa:'NNP'},
{en:'magic method', ko:'매직 메서드', pumsa:'NN'},
{en:'side effects', ko:'부수 효과', pumsa:'NNS'},
{en:'global state', ko:'전역 상태', pumsa:'NN'},
{en:'procedurally', ko:'절차적으로', pumsa:'RB'},
{en:'repositories', ko:'저장소', pumsa:'NNS'},
{en:'disadvantage', ko:'단점', pumsa:'NN'},
{en:'class object', ko:'클래스 객체', pumsa:'NN'},
{en:'dependencies', ko:'의존성', pumsa:'NNS'},
{en:'distribution', ko:'배포', pumsa:'NN'},
{en:'periodically', ko:'주기적으로', pumsa:'RB'},
{en:'environments', ko:'환경', pumsa:'NNS'},
{en:'definitions', ko:'정의', pumsa:'NNS'},
{en:'ignore case', ko:'대소문자를 무시', pumsa:'VBNN'},
{en:'abstraction', ko:'추상화', pumsa:'NN'},
{en:'equal signs', ko:'등호', pumsa:'NNS'},
{en:'most recent', ko:'최신', pumsa:'JJ'},
{en:'differences', ko:'차이', pumsa:'NNS'},
{en:'fundamental', ko:'기본적인', pumsa:'JJ_noun'},
{en:'development', ko:'개발', pumsa:'NN'},
{en:'Python code', ko:'파이썬 코드', pumsa:'NN'},
{en:'permissions', ko:'권한', pumsa:'NNS'},
{en:'Bash window', ko:'배시 창', pumsa:'NN'},
{en:'text editor', ko:'텍스트 에디터', pumsa:'NN'},
{en:'permissions', ko:'권한', pumsa:'NN'},
{en:'blank lines', ko:'빈 줄', pumsa:'NNS'},
{en:'environment', ko:'환경', pumsa:'NN'},
{en:'programming', ko:'프로그래밍', pumsa:'JJ'},
{en:'directories', ko:'디렉토리', pumsa:'NNS'},
{en:'linked list', ko:'링크드 리스트', pumsa:'NN'},
{en:'string form', ko:'문자열 형태', pumsa:'NN'},
{en:'concatenate', ko:'병합', pumsa:'VB'},
{en:'binary base', ko:'2진법', pumsa:'NN'},
{en:'compression', ko:'압축', pumsa:'NN'},
{en:'permutation', ko:'치환', pumsa:'NN'},
{en:'for example', ko:'예를 들어', pumsa:'RB'},
{en:'associative', ko:'연관된', pumsa:'JJ'},
{en:'byte arrays', ko:'바이트 어레이', pumsa:'NNS'},
{en:'proprieties', ko:'프로퍼티', pumsa:'NNS'},
{en:'spreadsheet', ko:'스프레드시트', pumsa:'NN'},
{en:'file object', ko:'파일 객체', pumsa:'NN'},
{en:'local scope', ko:'지역 스코프', pumsa:'NN'},
{en:'expressions', ko:'표현식', pumsa:'NNS'},
{en:'concatenate', ko:'병합', pumsa:'NN'},
{en:'combination', ko:'조합', pumsa:'NN'},
{en:'non-numeric', ko:'숫자가 아닌', pumsa:'JJ'},
{en:'iterability', ko:'이터러블', pumsa:'NN'},
{en:'hexadecimal', ko:'16진수', pumsa:'JJ'},
{en:'two or more', ko:'두 개 이상의', pumsa:'JJ'},
{en:'parentheses', ko:'괄호', pumsa:'NNS'},
{en:'information', ko:'정보', pumsa:'NN'},
{en:'whitespaces', ko:'공백 문자', pumsa:'NNS'},
{en:'interpreter', ko:'인터프리터', pumsa:'NN'},
{en:'performance', ko:'성능', pumsa:'NN'},
{en:'identifiers', ko:'식별자', pumsa:'NNS'},
{en:'child class', ko:'자식 클래스', pumsa:'NN'},
{en:'instantiate', ko:'인스턴스화', pumsa:'VB'},
{en:'maintaining', ko:'관리', pumsa:'VBG'},
{en:'collaborate', ko:'협업', pumsa:'VB'},
{en:'web servers', ko:'웹 서버', pumsa:'NNS'},
{en:'influential', ko:'영향력', pumsa:'JJ'},
{en:'influential', ko:'영향력 있는', pumsa:'JJ_noun'},
{en:'suggestions', ko:'제안', pumsa:'NNS'},
{en:'programmers', ko:'프로그래머', pumsa:'NNS'},
{en:'dollar sign', ko:'달러 기호', pumsa:'NN'},
{en:'start index', ko:'시작 인덱스', pumsa:'NN'},
{en:'backslashes', ko:'역슬래시', pumsa:'NNS'},
{en:'nationality', ko:'국적', pumsa:'NN'},
{en:'celebrities', ko:'유명인사', pumsa:'NNS'},
{en:'exactly one', ko:'단 하나', pumsa:'JJ'},
{en:'self-taught', ko:'독학하는', pumsa:'JJ'},
{en:'Programming', ko:'프로그래밍', pumsa:'NNP'},
{en:'programming', ko:'프로그래밍', pumsa:'VBG'},
{en:'encapsulate', ko:'캡슐화', pumsa:'VB'},
{en:'underscores', ko:'밑줄', pumsa:'NNS'},
{en:'description', ko:'설명', pumsa:'NN'},
{en:'in practice', ko:'실제로', pumsa:'RB'},
{en:'hidden file', ko:'히든 파일', pumsa:'NN'},
{en:'coordinates', ko:'좌표', pumsa:'NNS'},
{en:'most common', ko:'가장 널리 쓰이는', pumsa:'JJ'},
{en:'aggregation', ko:'통합', pumsa:'NN'},
{en:'Aggregation', ko:'통합', pumsa:'NNP'},
{en:'engineering', ko:'공학', pumsa:'NN'},
{en:'inheritance', ko:'상속', pumsa:'NN'},
{en:'Inheritance', ko:'상속', pumsa:'NNP'},
{en:'super class', ko:'슈퍼클래스', pumsa:'NN'},
{en:'dynamically', ko:'동적으로', pumsa:'RB'},
{en:'composition', ko:'합성', pumsa:'NN'},
{en:'programming', ko:'프로그래밍', pumsa:'NN'},
{en:'unnecessary', ko:'불필요', pumsa:'JJ'},
{en:'unnecessary', ko:'필요없는', pumsa:'JJ_noun'},
{en:'constructor', ko:'생성자', pumsa:'NN'},
{en:'descriptors', ko:'서술자', pumsa:'NNS'},
{en:'predictable', ko:'예측할 수 있는', pumsa:'JJ'},
{en:'exceptions', ko:'예외', pumsa:'NNS'},
{en:'programmer', ko:'프로그래머', pumsa:'NN'},
{en:'conditions', ko:'조건', pumsa:'NNS'},
{en:'descriptor', ko:'서술자', pumsa:'NN'},
{en:'attributes', ko:'속성', pumsa:'NNS'},
{en:'attributes', ko:'속성', pumsa:'VBZ'},
{en:'references', ko:'참조', pumsa:'NNS'},
{en:'predefined', ko:'미리 정의된', pumsa:'VBN'},
{en:'guarantees', ko:'보장', pumsa:'NNS'},
{en:'invocation', ko:'호출', pumsa:'NN'},
{en:'namespaces', ko:'네임스페이스', pumsa:'NNS'},
{en:'statically', ko:'정적으로', pumsa:'RB'},
{en:'principles', ko:'원칙', pumsa:'NNS'},
{en:'accessible', ko:'접근할 수 있는', pumsa:'JJ'},
{en:'base class', ko:'기반 클래스', pumsa:'NN'},
{en:'explicitly', ko:'명시적으로', pumsa:'RB'},
{en:'subclasses', ko:'서브클래스', pumsa:'NNS'},
{en:'superclass', ko:'슈퍼클래스', pumsa:'NN'},
{en:'serialized', ko:'직렬화된', pumsa:'JJ'},
{en:'Vocabulary', ko:'단어 해설', pumsa:'NNP'},
{en:'accidently', ko:'실수로', pumsa:'RB'},
{en:'docstrings', ko:'독스트링', pumsa:'NNS'},
{en:'particular', ko:'특정', pumsa:'JJ'},
{en:'illustrate', ko:'묘사', pumsa:'VB'},
{en:'convention', ko:'표기법', pumsa:'NN'},
{en:'text-based', ko:'텍스트 기반', pumsa:'JJ_noun'},
{en:'user input', ko:'사용자가 입력한 내용', pumsa:'NN'},
{en:'manipulate', ko:'조작', pumsa:'VB'},
{en:'every time', ko:'항상', pumsa:'RB'},
{en:'inner loop', ko:'내부 루프', pumsa:'NN'},
{en:'Washington', ko:'워싱턴', pumsa:'NNP'},
{en:'outer loop', ko:'외부 루프', pumsa:'NN'},
{en:'evaluation', ko:'평가', pumsa:'NN'},
{en:'class type', ko:'클래스 타입', pumsa:'NN'},
{en:'manageable', ko:'관리하기', pumsa:'JJ'},
{en:'manageable', ko:'관리하기 쉬운', pumsa:'JJ_noun'},
{en:'calculates', ko:'계산', pumsa:'VB'},
{en:'challenges', ko:'연습문제', pumsa:'NNS'},
{en:'Henceforth', ko:'여기서부터는', pumsa:'RB_Clause'},
{en:'rearranges', ko:'재배열', pumsa:'VB'},
{en:'Cunningham', ko:'커닝햄', pumsa:'NNP'},
{en:'underlying', ko:'기반이 되는', pumsa:'JJ_noun'},
{en:'data types', ko:'데이터 타입', pumsa:'NNS'},
{en:'presenting', ko:'부여', pumsa:'VBG'},
{en:'obligation', ko:'의무', pumsa:'NN'},
{en:'scoreboard', ko:'점수판', pumsa:'NN'},
{en:'statements', ko:'문', pumsa:'NNS'},
{en:'complexity', ko:'복잡도', pumsa:'NN'},
{en:'transverse', ko:'탐색', pumsa:'VB'},
{en:'algorithms', ko:'알고리즘', pumsa:'NN'},
{en:'whitespace', ko:'공백문자', pumsa:'NN'},
{en:'unpickling', ko:'언피클링', pumsa:'NN'},
{en:'almost any', ko:'거의 모든', pumsa:'JJ'},
{en:'collection', ko:'컬렉션', pumsa:'NN'},
{en:'Collection', ko:'컬렉션', pumsa:'NNP'},
{en:'repetition', ko:'반복', pumsa:'NN'},
{en:'on failure', ko:'실패했을 때', pumsa:'RB'},
{en:'comparison', ko:'비교', pumsa:'NN'},
{en:'difference', ko:'차이', pumsa:'NN'},
{en:'high-level', ko:'고수준', pumsa:'JJ'},
{en:'assignment', ko:'할당', pumsa:'NN'},
{en:'Player One', ko:'플레이어 1', pumsa:'NN'},
{en:'predefined', ko:'미리 정의된', pumsa:'JJ'},
{en:'electrical', ko:'전기적', pumsa:'JJ'},
{en:'Player Two', ko:'플레이어 2', pumsa:'NN'},
{en:'properties', ko:'프로퍼티', pumsa:'NNS'},
{en:'membership', ko:'멤버', pumsa:'NN'},
{en:'mutability', ko:'가변성', pumsa:'NN'},
{en:'characters', ko:'문자', pumsa:'NNS'},
{en:'underscore', ko:'밑줄', pumsa:'NN'},
{en:'dimensions', ko:'차원', pumsa:'NNS'},
{en:'palindrome', ko:'회문', pumsa:'NN'},
{en:'structures', ko:'구조', pumsa:'NNS'},
{en:'operations', ko:'연산', pumsa:'NNS'},
{en:'by default', ko:'기본적으로', pumsa:'RB'},
{en:'efficiency', ko:'효율', pumsa:'NN'},
{en:'expression', ko:'표현식', pumsa:'NN'},
{en:'management', ko:'관리', pumsa:'NN'},
{en:'hair color', ko:'머리카락 색깔', pumsa:'NN'},
{en:'individual', ko:'개별', pumsa:'JJ'},
{en:'dictionary', ko:'딕셔너리', pumsa:'JJ'},
{en:'Challenges', ko:'연습문제', pumsa:'NNP'},
{en:'serialized', ko:'직렬화된', pumsa:'VBN'},
{en:'represents', ko:'나타', pumsa:'VB'},
{en:'file paths', ko:'파일 경로', pumsa:'NNS'},
{en:'understand', ko:'이해', pumsa:'VB'},
{en:'byte array', ko:'바이트 어레이', pumsa:'NN'},
{en:'containers', ko:'컨테이너', pumsa:'NNS'},
{en:'at the end', ko:'마지막에', pumsa:'RB'},
{en:'search for', ko:'검색', pumsa:'VB'},
{en:'definition', ko:'정의', pumsa:'NN'},
{en:'parameters', ko:'매개변수', pumsa:'NNS'},
{en:'duplicates', ko:'중복', pumsa:'NNS'},
{en:'singletons', ko:'싱글톤', pumsa:'NNS'},
{en:'distribute', ko:'배포', pumsa:'VB'},
{en:'insertions', ko:'삽입', pumsa:'NNS'},
{en:'dictionary', ko:'딕셔너리', pumsa:'NN'},
{en:'generators', ko:'제네레이터', pumsa:'NNS'},
{en:'in general', ko:'일반적으로', pumsa:'RB'},
{en:'Easter egg', ko:'이스터 에그', pumsa:'NN'},
{en:'non-greedy', ko:'소극적', pumsa:'JJ'},
{en:'non-greedy', ko:'소극적인', pumsa:'JJ_noun'},
{en:'very first', ko:'맨 처음', pumsa:'JJ_noun'},
{en:'Windows 10', ko:'윈도우 10', pumsa:'NNP'},
{en:'navigating', ko:'이동', pumsa:'VBG'},
{en:'unintended', ko:'의도하지 않은', pumsa:'JJ_noun'},
{en:'frequently', ko:'자주', pumsa:'RB'},
{en:'unexpected', ko:'의도하지 않은', pumsa:'JJ'},
{en:'unexpected', ko:'의도하지 않은', pumsa:'JJ_noun'},
{en:'impossible', ko:'불가능', pumsa:'JJ'},
{en:'advantages', ko:'장점', pumsa:'NNS'},
{en:'class name', ko:'클래스 이름', pumsa:'NN'},
{en:'code reuse', ko:'코드 재사용', pumsa:'NN'},
{en:'functional', ko:'동작', pumsa:'JJ'},
{en:'functional', ko:'함수형', pumsa:'JJ_noun'},
{en:'procedural', ko:'절차적', pumsa:'JJ'},
{en:'procedural', ko:'절차적', pumsa:'JJ_noun'},
{en:'Stroustrup', ko:'스트롭스트룹', pumsa:'NNP'},
{en:'surrounded', ko:'둘러싸인', pumsa:'VBN'},
{en:'organizing', ko:'정리', pumsa:'VB'},
{en:'repository', ko:'저장소', pumsa:'NN'},
{en:'developers', ko:'개발자', pumsa:'NNS'},
{en:'frameworks', ko:'프레임워크', pumsa:'NNS'},
{en:'downloaded', ko:'내려받', pumsa:'VBN'},
{en:'particular', ko:'특정', pumsa:'JJ_noun'},
{en:'containing', ko:'포함', pumsa:'VBG'},
{en:'passing in', ko:'전달', pumsa:'VBG'},
{en:'initialize', ko:'초기화', pumsa:'VB'},
{en:'web server', ko:'웹 서버', pumsa:'NN'},
{en:'strongest', ko:'가장 강한', pumsa:'JJ_noun'},
{en:'uninstall', ko:'제거', pumsa:'VB'},
{en:'drop-down', ko:'드롭다운', pumsa:'JJ'},
{en:'no longer', ko:'더는', pumsa:'RB'},
{en:'passed in', ko:'전달', pumsa:'VB'},
{en:'inherited', ko:'상속된', pumsa:'JJ_noun'},
{en:'each time', ko:'때마다', pumsa:'WRB'},
{en:'typically', ko:'일반적으로', pumsa:'RB'},
{en:'paragraph', ko:'문단', pumsa:'NN'},
{en:'replacing', ko:'교체', pumsa:'VBG'},
{en:'paradigms', ko:'패러다임', pumsa:'NN'},
{en:'framework', ko:'프레임워크', pumsa:'NN'},
{en:'perimeter', ko:'둘레', pumsa:'NN'},
{en:'rectangle', ko:'사각형', pumsa:'NN'},
{en:'camelcase', ko:'카멜 케이스', pumsa:'NN'},
{en:'installed', ko:'설치', pumsa:'VBN'},
{en:'very last', ko:'맨 마지막', pumsa:'JJ_noun'},
{en:'reference', ko:'참조', pumsa:'VB'},
{en:'root user', ko:'루트 사용자', pumsa:'NN'},
{en:'installed', ko:'설치', pumsa:'VB'},
{en:'re-insert', ko:'다시 삽입', pumsa:'VB'},
{en:'container', ko:'컨테이너', pumsa:'NN'},
{en:'read-only', ko:'읽기 전용', pumsa:'JJ'},
{en:'frequency', ko:'빈도', pumsa:'NN'},
{en:'recurring', ko:'반복되는', pumsa:'VBG'},
{en:'ethnicity', ko:'민족', pumsa:'NN'},
{en:'languages', ko:'언어', pumsa:'NNS'},
{en:'optimized', ko:'최적화된', pumsa:'VBN'},
{en:'appending', ko:'이어붙임', pumsa:'VBG'},
{en:'procedure', ko:'프로시저', pumsa:'NN'},
{en:'directory', ko:'디렉토리', pumsa:'NN'},
{en:'searching', ko:'검색', pumsa:'NN'},
{en:'continued', ko:'연속적인', pumsa:'JJ'},
{en:'benchmark', ko:'벤치마크', pumsa:'NN'},
{en:'unordered', ko:'순서 없는', pumsa:'JJ'},
{en:'duplicate', ko:'중복', pumsa:'NN'},
{en:'duplicate', ko:'중복된', pumsa:'JJ'},
{en:'accessing', ko:'접근', pumsa:'VBG'},
{en:'unix-like', ko:'유닉스 계열', pumsa:'JJ'},
{en:'unix-like', ko:'유닉스 계열', pumsa:'JJ_noun'},
{en:'delimiter', ko:'구분자', pumsa:'NN'},
{en:'separates', ko:'구분', pumsa:'VB'},
{en:'CSV files', ko:'CSV 파일', pumsa:'NNS'},
{en:'solutions', ko:'해답', pumsa:'NNS'},
{en:'less than', ko:'보다 작은', pumsa:'JJR'},
{en:'searching', ko:'검색', pumsa:'VBG'},
{en:'automatic', ko:'자동', pumsa:'JJ'},
{en:'condition', ko:'조건', pumsa:'NN'},
{en:'benchmark', ko:'벤치마크', pumsa:'VB'},
{en:'arguments', ko:'매개변수', pumsa:'NNS'},
{en:'iteration', ko:'순회', pumsa:'NN'},
{en:'parameter', ko:'매개변수', pumsa:'NN'},
{en:'statement', ko:'문', pumsa:'NN'},
{en:'immutable', ko:'불변', pumsa:'JJ'},
{en:'bytearray', ko:'바이트 어레이', pumsa:'NN'},
{en:'operation', ko:'연산', pumsa:'NN'},
{en:'attribute', ko:'속성', pumsa:'NN'},
{en:'sequences', ko:'시퀀스', pumsa:'NNS'},
{en:'recursive', ko:'재귀', pumsa:'JJ'},
{en:'computers', ko:'컴퓨터', pumsa:'NNS'},
{en:'exception', ko:'예외', pumsa:'NN'},
{en:'unpacking', ko:'분해', pumsa:'VBG'},
{en:'addresses', ko:'해결', pumsa:'VB'},
{en:'iterators', ko:'이터레이터', pumsa:'NNS'},
{en:'represent', ko:'표현', pumsa:'VB'},
{en:'generator', ko:'제네레이터', pumsa:'NN'},
{en:'propriety', ko:'프로퍼티', pumsa:'NN'},
{en:'dimension', ko:'차원', pumsa:'NN'},
{en:'arbitrary', ko:'임의의', pumsa:'JJ'},
{en:'character', ko:'문자', pumsa:'NN'},
{en:'unpacking', ko:'분해', pumsa:'NN'},
{en:'key-value', ko:'키-값', pumsa:'JJ'},
{en:'lowercase', ko:'소문자', pumsa:'NN'},
{en:'substring', ko:'부분 문자열', pumsa:'VBG'},
{en:'uppercase', ko:'대문자', pumsa:'JJ'},
{en:'remainder', ko:'나머지', pumsa:'NN'},
{en:'Fibonacci', ko:'피보나치', pumsa:'NNP'},
{en:'beginning', ko:'처음', pumsa:'NN'},
{en:'uppercase', ko:'대문자', pumsa:'NN'},
{en:'extension', ko:'확장자', pumsa:'NN'},
{en:'variables', ko:'변수', pumsa:'NNS'},
{en:'insertion', ko:'삽입', pumsa:'NN'},
{en:'if needed', ko:'필요하다면', pumsa:'RB'},
{en:'innermost', ko:'가장 안쪽의', pumsa:'NN'},
{en:'structure', ko:'구조', pumsa:'NN'},
{en:'exponents', ko:'지수', pumsa:'NNS'},
{en:'precision', ko:'정밀도', pumsa:'NN'},
{en:'efficient', ko:'효율적', pumsa:'JJ'},
{en:'eye color', ko:'눈 색깔', pumsa:'NN'},
{en:'di?erence', ko:'차이', pumsa:'NN'},
{en:'currently', ko:'현재', pumsa:'RB'},
{en:'reference', ko:'참조', pumsa:'NN'},
{en:'important', ko:'중요', pumsa:'JJ'},
{en:'important', ko:'중요한', pumsa:'JJ_noun'},
{en:'repeating', ko:'반복', pumsa:'VBG'},
{en:'presented', ko:'부여', pumsa:'VB'},
{en:'triangles', ko:'삼각형', pumsa:'NNS'},
{en:'different', ko:'다른', pumsa:'JJ_noun'},
{en:'essential', ko:'핵심', pumsa:'JJ'},
{en:'essential', ko:'핵심적인', pumsa:'JJ_noun'},
{en:'interface', ko:'인터페이스', pumsa:'NN'},
{en:'advantage', ko:'장점', pumsa:'NN'},
{en:'mechanism', ko:'메커니즘', pumsa:'NN'},
{en:'card game', ko:'카드 게임', pumsa:'NN'},
{en:'overrides', ko:'오버라이드', pumsa:'VB'},
{en:'inherited', ko:'상속', pumsa:'VBN'},
{en:'Smalltalk', ko:'스몰토크', pumsa:'NNP'},
{en:'pioneered', ko:'개척', pumsa:'VB'},
{en:'questions', ko:'질문', pumsa:'NNS'},
{en:'evaluates', ko:'평가', pumsa:'VB'},
{en:'following', ko:'다음', pumsa:'JJ'},
{en:'following', ko:'다음', pumsa:'JJ_noun'},
{en:'calculate', ko:'계산', pumsa:'VB'},
{en:'community', ko:'커뮤니티', pumsa:'NN'},
{en:'resources', ko:'자료', pumsa:'NNS'},
{en:'file path', ko:'파일 경로', pumsa:'NN'},
{en:'iterables', ko:'이터러블', pumsa:'NNS'},
{en:'backslash', ko:'백슬래시', pumsa:'NN'},
{en:'iterating', ko:'순회', pumsa:'VBG'},
{en:'end index', ko:'끝 인덱스', pumsa:'NN'},
{en:'challenge', ko:'연습문제', pumsa:'NN'},
{en:'iterables', ko:'이터러블', pumsa:'NN'},
{en:'musicians', ko:'음악가', pumsa:'NNS'},
{en:'make sure', ko:'확인', pumsa:'VB'},
{en:'Paradigms', ko:'패러다임', pumsa:'NNP'},
{en:'citations', ko:'인용', pumsa:'NNS'},
{en:'less than', ko:'보다 작은', pumsa:'JJ'},
{en:'situation', ko:'상황', pumsa:'NN'},
{en:'docstring', ko:'독스트링', pumsa:'NN'},
{en:'longitude', ko:'경도', pumsa:'NN'},
{en:'data type', ko:'데이터 타입', pumsa:'NN'},
{en:'observers', ko:'옵저버', pumsa:'NNS'},
{en:'decorator', ko:'데코레이터', pumsa:'NN'},
{en:'read-only', ko:'읽기 전용', pumsa:'RB'},
{en:'Singleton', ko:'싱글톤', pumsa:'NNP'},
{en:'singleton', ko:'싱글톤', pumsa:'NN'},
{en:'correctly', ko:'정확히', pumsa:'RB'},
{en:'Decorator', ko:'데코레이터', pumsa:'NNP'},
{en:'elegantly', ko:'우아하게', pumsa:'RB'},
{en:'functions', ko:'함수', pumsa:'NNS'},
{en:'principle', ko:'원칙', pumsa:'NN'},
{en:'redefined', ko:'재정의', pumsa:'VBN'},
{en:'namespace', ko:'네임스페이스', pumsa:'NN'},
{en:'top-level', ko:'최상위', pumsa:'JJ'},
{en:'capturing', ko:'캡처', pumsa:'VBG'},
{en:'instances', ko:'인스턴스', pumsa:'NNS'},
{en:'attribute', ko:'속성', pumsa:'JJ'},
{en:'carefully', ko:'주의 깊게', pumsa:'RB'},
{en:'traceback', ko:'트레이스백', pumsa:'NN'},
{en:'outermost', ko:'가장 바깥에 있는', pumsa:'NN'},
{en:'execution', ko:'실행', pumsa:'NN'},
{en:'unhandled', ko:'처리하지 않은', pumsa:'JJ'},
{en:'matching', ko:'일치하는', pumsa:'JJ'},
{en:'clean-up', ko:'마무리', pumsa:'NN'},
{en:'response', ko:'응답', pumsa:'NN'},
{en:'writable', ko:'쓰기 가능', pumsa:'JJ'},
{en:'removing', ko:'제거', pumsa:'VBG'},
{en:'approach', ko:'접근법', pumsa:'NN'},
{en:'subclass', ko:'서브클래스', pumsa:'NN'},
{en:'inherits', ko:'상속', pumsa:'VBZ'},
{en:'ordinary', ko:'평범한', pumsa:'JJ'},
{en:'software', ko:'소프트웨어', pumsa:'NN'},
{en:'designed', ko:'설계된', pumsa:'VBN'},
{en:'instance', ko:'인스턴스', pumsa:'NN'},
{en:'previous', ko:'이전', pumsa:'JJ'},
{en:'previous', ko:'이전', pumsa:'JJ_noun'},
{en:'Observer', ko:'옵저버', pumsa:'NNP'},
{en:'observer', ko:'옵저버', pumsa:'NN'},
{en:'syntaxes', ko:'문법', pumsa:'NNS'},
{en:'latitude', ko:'위도', pumsa:'NN'},
{en:'flexible', ko:'유연', pumsa:'JJ'},
{en:'flexible', ko:'유연한', pumsa:'JJ_noun'},
{en:'in pairs', ko:'짝지어서', pumsa:'RB'},
{en:'document', ko:'문서화', pumsa:'VB'},
{en:'handling', ko:'처리', pumsa:'VBG'},
{en:'specific', ko:'특정', pumsa:'JJ'},
{en:'specific', ko:'특정', pumsa:'JJ_noun'},
{en:'keywords', ko:'키워드', pumsa:'NNS'},
{en:'mistakes', ko:'실수', pumsa:'NNS'},
{en:'behavior', ko:'작동 방식', pumsa:'NN'},
{en:'Disraeli', ko:'디즈레일리', pumsa:'NNP'},
{en:'language', ko:'언어', pumsa:'NN'},
{en:'collects', ko:'수집', pumsa:'NNS'},
{en:'CSV file', ko:'CSV 파일', pumsa:'NN'},
{en:'programs', ko:'프로그램', pumsa:'NNS'},
{en:'concepts', ko:'개념', pumsa:'NNS'},
{en:'benjamin', ko:'벤자민', pumsa:'NN'},
{en:'practice', ko:'연습', pumsa:'NN'},
{en:'managers', ko:'관리자', pumsa:'NNS'},
{en:'part iii', ko:'3부', pumsa:'NN'},
{en:'collects', ko:'수집', pumsa:'VBZ'},
{en:'favorite', ko:'좋아하는', pumsa:'JJ_noun'},
{en:'New York', ko:'뉴욕', pumsa:'NNP'},
{en:'iterable', ko:'이터러블', pumsa:'NN'},
{en:'escaping', ko:'이스케이프', pumsa:'NN'},
{en:'original', ko:'원래', pumsa:'JJ'},
{en:'original', ko:'원래', pumsa:'JJ_noun'},
{en:'greedily', ko:'적극적으로', pumsa:'RB'},
{en:'escaping', ko:'이스케이프', pumsa:'VBG'},
{en:'dialogue', ko:'대화', pumsa:'NN'},
{en:'sentence', ko:'문장', pumsa:'NN'},
{en:'executes', ko:'실행', pumsa:'VB'},
{en:'populate', ko:'생성', pumsa:'VB'},
{en:'Facebook', ko:'페이스북', pumsa:'NNP'},
{en:'friendly', ko:'친절', pumsa:'JJ'},
{en:'projects', ko:'프로젝트', pumsa:'NNS'},
{en:'computer', ko:'컴퓨터', pumsa:'NN'},
{en:'multiple', ko:'여러', pumsa:'JJ_noun'},
{en:'built-in', ko:'내장', pumsa:'JJ'},
{en:'built-in', ko:'내장', pumsa:'JJ_noun'},
{en:'question', ko:'질문', pumsa:'NN'},
{en:'utilizes', ko:'활용', pumsa:'VB'},
{en:'overrode', ko:'오버라이드', pumsa:'VB'},
{en:'operands', ko:'피연산자', pumsa:'NNS'},
{en:'evaluate', ko:'평가', pumsa:'VB'},
{en:'override', ko:'오버라이드', pumsa:'VB'},
{en:'patterns', ko:'패턴', pumsa:'NNS'},
{en:'Internet', ko:'인터넷', pumsa:'NNP'},
{en:'modeling', ko:'모델화', pumsa:'VBG'},
{en:'inherits', ko:'상속', pumsa:'VB'},
{en:'defining', ko:'정의', pumsa:'VBG'},
{en:'variable', ko:'변수', pumsa:'JJ'},
{en:'mantissa', ko:'가수', pumsa:'NN'},
{en:'exponent', ko:'지수', pumsa:'NN'},
{en:'compiler', ko:'컴파일러', pumsa:'NN'},
{en:'elements', ko:'요소', pumsa:'NNS'},
{en:'Computer', ko:'컴퓨터', pumsa:'NNP'},
{en:'notation', ko:'표기법', pumsa:'NN'},
{en:'abstract', ko:'추상', pumsa:'NN'},
{en:'elements', ko:'요소', pumsa:'VBZ'},
{en:'pickling', ko:'피클링', pumsa:'NN'},
{en:'encoding', ko:'인코딩', pumsa:'NN'},
{en:'sequence', ko:'시퀀스', pumsa:'NN'},
{en:'versions', ko:'버전', pumsa:'NNS'},
{en:'division', ko:'나눗셈', pumsa:'NN'},
{en:'operator', ko:'연산자', pumsa:'NN'},
{en:'quotient', ko:'몫', pumsa:'NN'},
{en:'greatest', ko:'가장 큰', pumsa:'JJS'},
{en:'position', ko:'위치', pumsa:'NN'},
{en:'standard', ko:'표준', pumsa:'JJ'},
{en:'paradigm', ko:'패러다임', pumsa:'NN'},
{en:'equality', ko:'일치', pumsa:'NN'},
{en:'iterable', ko:'이터러블', pumsa:'JJ'},
{en:'unsigned', ko:'부호 없는', pumsa:'JJ'},
{en:'function', ko:'함수', pumsa:'NN'},
{en:'variable', ko:'변수', pumsa:'NN'},
{en:'decimals', ko:'10진수', pumsa:'NNS'},
{en:'argument', ko:'매개변수', pumsa:'NN'},
{en:'integers', ko:'정수', pumsa:'NNS'},
{en:'matrices', ko:'행렬', pumsa:'NNS'},
{en:'randomly', ko:'무작위로', pumsa:'RB'},
{en:'iterator', ko:'이터레이터', pumsa:'NN'},
{en:'protocol', ko:'프로토콜', pumsa:'NN'},
{en:'replaces', ko:'교체', pumsa:'VB'},
{en:'problems', ko:'문제', pumsa:'NNS'},
{en:'pointers', ko:'포인터', pumsa:'NNS'},
{en:'examples', ko:'예제', pumsa:'NNS'},
{en:'solution', ko:'해답', pumsa:'NN'},
{en:'analysis', ko:'분석', pumsa:'NN'},
{en:'optional', ko:'옵션', pumsa:'JJ'},
{en:'brackets', ko:'대괄호', pumsa:'NNS'},
{en:'suitable', ko:'적절한', pumsa:'JJ'},
{en:'property', ko:'프로퍼티', pumsa:'NN'},
{en:'in order', ko:'순서대로', pumsa:'RB'},
{en:'required', ko:'필수', pumsa:'VBN'},
{en:'required', ko:'필수', pumsa:'JJ'},
{en:'separate', ko:'구분', pumsa:'VB'},
{en:'location', ko:'위치', pumsa:'NN'},
{en:'Benjamin', ko:'벤자민', pumsa:'NNP'},
{en:'constant', ko:'일정한', pumsa:'JJ'},
{en:'normally', ko:'보통', pumsa:'RB_Clause'},
{en:'a single', ko:'하나', pumsa:'NN'},
{en:'packages', ko:'패키지', pumsa:'NNS'},
{en:'directly', ko:'직접', pumsa:'RB'},
{en:'compiled', ko:'컴파일된', pumsa:'VBD'},
{en:'implicit', ko:'암시적', pumsa:'JJ'},
{en:'existing', ko:'기존', pumsa:'VBG'},
{en:'contents', ko:'콘텐츠', pumsa:'NNS'},
{en:'handling', ko:'처리', pumsa:'NN'},
{en:'anagrams', ko:'애너그램', pumsa:'NNS'},
{en:'powerful', ko:'강력한', pumsa:'JJ_noun'},
{en:'security', ko:'보안', pumsa:'NN'},
{en:'username', ko:'사용자 이름', pumsa:'NN'},
{en:'password', ko:'비밀번호', pumsa:'NN'},
{en:'matching', ko:'일치', pumsa:'NN'},
{en:'Mad Libs', ko:'매드립스', pumsa:'NNP'},
{en:'simplest', ko:'가장 단순한', pumsa:'JJ_noun'},
{en:'branches', ko:'가지', pumsa:'NNS'},
{en:'relative', ko:'상대', pumsa:'JJ_noun'},
{en:'absolute', ko:'절대', pumsa:'JJ_noun'},
{en:'commands', ko:'명령어', pumsa:'NNS'},
{en:'installs', ko:'설치', pumsa:'VB'},
{en:'purposes', ko:'목적', pumsa:'NNS'},
{en:'physical', ko:'물리적', pumsa:'JJ'},
{en:'physical', ko:'물리적', pumsa:'JJ_noun'},
{en:'complain', ko:'불평', pumsa:'VB'},
{en:'executed', ko:'실행', pumsa:'VB'},
{en:'codebase', ko:'코드베이스', pumsa:'NN'},
{en:'websites', ko:'웹사이트', pumsa:'NNS'},
{en:'download', ko:'내려받', pumsa:'VB'},
{en:'returned', ko:'반환', pumsa:'VB'},
{en:'asterisk', ko:'애스터리스크', pumsa:'NN'},
{en:'metadata', ko:'메타데이터', pumsa:'NN'},
{en:'properly', ko:'제대로', pumsa:'RB'},
{en:'internal', ko:'내부', pumsa:'JJ_noun'},
{en:'contains', ko:'포함', pumsa:'VB'},
{en:'navigate', ko:'이동', pumsa:'VB'},
{en:'instead', ko:'대신', pumsa:'RB_Clause'},
{en:'ignored', ko:'무시', pumsa:'VB'},
{en:'options', ko:'옵션', pumsa:'NNS'},
{en:'account', ko:'계정', pumsa:'NN'},
{en:'virtual', ko:'가상', pumsa:'JJ'},
{en:'virtual', ko:'가상', pumsa:'JJ_noun'},
{en:'Shivers', ko:'시버스', pumsa:'NNP'},
{en:'changes', ko:'변경', pumsa:'VB'},
{en:'browser', ko:'브라우저', pumsa:'NN'},
{en:'quickly', ko:'빠르게', pumsa:'RB'},
{en:'created', ko:'만들어진', pumsa:'VBN'},
{en:'created', ko:'생성', pumsa:'VB'},
{en:'methods', ko:'메서드', pumsa:'NN'},
{en:'operand', ko:'피연산자', pumsa:'NN'},
{en:'install', ko:'설치', pumsa:'VB'},
{en:'need to', ko:'해야', pumsa:'MD'},
{en:'replace', ko:'교체', pumsa:'VB'},
{en:'website', ko:'웹사이트', pumsa:'NN'},
{en:'project', ko:'프로젝트', pumsa:'NN'},
{en:'Part IV', ko:'4부', pumsa:'NNP'},
{en:'service', ko:'서비스', pumsa:'NN'},
{en:'changes', ko:'변화', pumsa:'NNS'},
{en:'make up', ko:'구성', pumsa:'VB'},
{en:'manager', ko:'매니저', pumsa:'NN'},
{en:'manages', ko:'관리', pumsa:'VB'},
{en:'however', ko:'하지만', pumsa:'RB'},
{en:'accepts', ko:'받', pumsa:'VB'},
{en:'formula', ko:'공식', pumsa:'NN'},
{en:'several', ko:'여러 가지', pumsa:'JJ_noun'},
{en:'regular', ko:'일반적', pumsa:'JJ'},
{en:'regular', ko:'일반적인', pumsa:'JJ_noun'},
{en:'finally', ko:'마지막으로', pumsa:'RB'},
{en:'address', ko:'해결', pumsa:'VB'},
{en:'windows', ko:'윈도우', pumsa:'NNS'},
{en:'web app', ko:'웹 앱', pumsa:'NN'},
{en:'address', ko:'주소', pumsa:'NN'},
{en:'current', ko:'현재', pumsa:'JJ_noun'},
{en:'matches', ko:'일치', pumsa:'VB'},
{en:'anagram', ko:'애너그램', pumsa:'NN'},
{en:'Counter', ko:'카운터', pumsa:'NNP'},
{en:'default', ko:'기본', pumsa:'NN'},
{en:'ordered', ko:'순서 있는', pumsa:'JJ'},
{en:'command', ko:'명령', pumsa:'NN'},
{en:'writing', ko:'쓰기', pumsa:'NN'},
{en:'numeric', ko:'숫자형', pumsa:'JJ'},
{en:'boolean', ko:'불리언', pumsa:'JJ'},
{en:'certain', ko:'특정', pumsa:'JJ'},
{en:'usually', ko:'보통', pumsa:'RB'},
{en:'hashing', ko:'해시', pumsa:'VBG'},
{en:'execute', ko:'실행', pumsa:'VB'},
{en:'ignores', ko:'무시', pumsa:'VBZ'},
{en:'outside', ko:'외부', pumsa:'NN'},
{en:'Windows', ko:'윈도우', pumsa:'NNP'},
{en:'encoded', ko:'인코드된', pumsa:'VBD'},
{en:'compile', ko:'컴파일', pumsa:'VBP'},
{en:'calling', ko:'호출', pumsa:'NN'},
{en:'content', ko:'콘텐츠', pumsa:'NN'},
{en:'Garbage', ko:'가비지', pumsa:'NNP'},
{en:'garbage', ko:'가비지', pumsa:'NN'},
{en:'related', ko:'연관된', pumsa:'JJ'},
{en:'runtime', ko:'런타임', pumsa:'JJ'},
{en:'symbols', ko:'기호', pumsa:'NNS'},
{en:'Bitwise', ko:'비트', pumsa:'NNP'},
{en:'bitwise', ko:'비트', pumsa:'VB'},
{en:'million', ko:'백만', pumsa:'CD'},
{en:'results', ko:'결과', pumsa:'NNS'},
{en:'pattern', ko:'패턴', pumsa:'NN'},
{en:'benefit', ko:'이득', pumsa:'NN'},
{en:'guesses', ko:'짐작', pumsa:'VB'},
{en:'feature', ko:'기능', pumsa:'NN'},
{en:'library', ko:'라이브러리', pumsa:'NN'},
{en:'general', ko:'일반적', pumsa:'JJ'},
{en:'example', ko:'예제', pumsa:'NN'},
{en:'numbers', ko:'숫자', pumsa:'NNS'},
{en:'returns', ko:'반환', pumsa:'VBZ'},
{en:'methods', ko:'메서드', pumsa:'NNS'},
{en:'Hangman', ko:'행맨', pumsa:'NNP'},
{en:'snippet', ko:'코드', pumsa:'NN'},
{en:'control', ko:'제어권', pumsa:'NN'},
{en:'failure', ko:'실패', pumsa:'NN'},
{en:'element', ko:'요소', pumsa:'NN'},
{en:'section', ko:'섹션', pumsa:'NN'},
{en:'16-bits', ko:'16비트', pumsa:'NNS'},
{en:'mapping', ko:'매핑', pumsa:'NN'},
{en:'context', ko:'컨텍스트', pumsa:'NN'},
{en:'another', ko:'다른', pumsa:'DT'},
{en:'compare', ko:'비교', pumsa:'VB'},
{en:'problem', ko:'문제', pumsa:'NN'},
{en:'fingers', ko:'손가락', pumsa:'NNS'},
{en:'package', ko:'패키지', pumsa:'NN'},
{en:'chapter', ko:'장', pumsa:'NN'},
{en:'copying', ko:'복사', pumsa:'NN'},
{en:'process', ko:'작업', pumsa:'NN'},
{en:'convert', ko:'변환', pumsa:'VB'},
{en:'require', ko:'요구', pumsa:'VB'},
{en:'concept', ko:'개념', pumsa:'NN'},
{en:'Unicode', ko:'유니코드', pumsa:'NNP'},
{en:'program', ko:'프로그램', pumsa:'NN'},
{en:'runtime', ko:'런타임', pumsa:'NN'},
{en:'closest', ko:'가장 가까운', pumsa:'JJS'},
{en:'dynamic', ko:'동적', pumsa:'JJ'},
{en:'Science', ko:'과학', pumsa:'NNP'},
{en:'decimal', ko:'10진', pumsa:'JJ'},
{en:'printed', ko:'출력', pumsa:'VB'},
{en:'integer', ko:'정수', pumsa:'NN'},
{en:'machine', ko:'컴퓨터', pumsa:'NN'},
{en:'support', ko:'지원', pumsa:'VB'},
{en:'present', ko:'부여', pumsa:'VB'},
{en:'passing', ko:'전달', pumsa:'VBG'},
{en:'squares', ko:'사각형', pumsa:'NNS'},
{en:'circles', ko:'원', pumsa:'NNS'},
{en:'callers', ko:'호출자', pumsa:'NNS'},
{en:'smaller', ko:'더 작', pumsa:'JJ'},
{en:'smaller', ko:'더 작은', pumsa:'JJ_noun'},
{en:'smaller', ko:'더 작고', pumsa:'JJ_and'},
{en:'creates', ko:'생성', pumsa:'VB'},
{en:'complex', ko:'복잡', pumsa:'JJ'},
{en:'complex', ko:'복잡한', pumsa:'JJ_noun'},
{en:'special', ko:'특별한', pumsa:'JJ_noun'},
{en:'toggles', ko:'토글', pumsa:'VB'},
{en:'picture', ko:'그림', pumsa:'NN'},
{en:'classes', ko:'클래스', pumsa:'NNS'},
{en:'oranges', ko:'오렌지', pumsa:'NNS'},
{en:'assigns', ko:'할당', pumsa:'VB'},
{en:'popular', ko:'인기 있는', pumsa:'JJ_noun'},
{en:'highest', ko:'가장 높은', pumsa:'JJ_noun'},
{en:'defined', ko:'정의된', pumsa:'VBN'},
{en:'storing', ko:'저장', pumsa:'VBG'},
{en:'parents', ko:'부모', pumsa:'NNS'},
{en:'inherit', ko:'상속', pumsa:'VB'},
{en:'related', ko:'연관된', pumsa:'VBN'},
{en:'combine', ko:'조합', pumsa:'VB'},
{en:'various', ko:'다양', pumsa:'JJ'},
{en:'various', ko:'다양한', pumsa:'JJ_noun'},
{en:'forever', ko:'영원히', pumsa:'RB'},
{en:'someone', ko:'누군가', pumsa:'NN'},
{en:'helpful', ko:'도움이 되는', pumsa:'JJ_noun'},
{en:'helpful', ko:'도움이 되고', pumsa:'JJ_and'},
{en:'returns', ko:'반환', pumsa:'NNS'},
{en:'display', ko:'표시', pumsa:'VB'},
{en:'letters', ko:'글자', pumsa:'NNS'},
{en:'hangman', ko:'행맨', pumsa:'NN'},
{en:'folders', ko:'폴더', pumsa:'NNS'},
{en:'slashes', ko:'슬래시', pumsa:'NNS'},
{en:'mutable', ko:'가변', pumsa:'JJ'},
{en:'mutable', ko:'가변', pumsa:'JJ_noun'},
{en:'execute', ko:'실행', pumsa:'NN'},
{en:'correct', ko:'정확한', pumsa:'JJ_noun'},
{en:'newline', ko:'줄바꿈', pumsa:'NN'},
{en:'slicing', ko:'슬라이스', pumsa:'NN'},
{en:'pass in', ko:'전달', pumsa:'VB'},
{en:'special', ko:'특별', pumsa:'JJ'},
{en:'meaning', ko:'의미', pumsa:'NN'},
{en:'returns', ko:'반환', pumsa:'VB'},
{en:'rappers', ko:'래퍼', pumsa:'NNS'},
{en:'rockers', ko:'라커', pumsa:'NNS'},
{en:'pillars', ko:'기둥', pumsa:'NNS'},
{en:'Althoff', ko:'알토프', pumsa:'NNP'},
{en:'version', ko:'버전', pumsa:'NN'},
{en:'explain', ko:'설명', pumsa:'VB'},
{en:'algebra', ko:'수학', pumsa:'VB'},
{en:'keyword', ko:'키워드', pumsa:'NN'},
{en:'calling', ko:'호출', pumsa:'VBG'},
{en:'reusing', ko:'재사용', pumsa:'VBG'},
{en:'comment', ko:'주석', pumsa:'NN'},
{en:'outside', ko:'외부', pumsa:'IN'},
{en:'execute', ko:'실행', pumsa:'VBP'},
{en:'part II', ko:'2부', pumsa:'NN'},
{en:'similar', ko:'비슷', pumsa:'JJ'},
{en:'similar', ko:'비슷한', pumsa:'JJ_noun'},
{en:'strings', ko:'문자열', pumsa:'NNS'},
{en:'Abraham', ko:'에이브러햄', pumsa:'NNP'},
{en:'Lincoln', ko:'링컨', pumsa:'NNP'},
{en:'exactly', ko:'정확히', pumsa:'RB'},
{en:'defines', ko:'정의', pumsa:'VBZ'},
{en:'specify', ko:'명시', pumsa:'VB'},
{en:'highest', ko:'최상위', pumsa:'JJS'},
{en:'details', ko:'세부', pumsa:'NNS'},
{en:'textual', ko:'어휘적', pumsa:'JJ'},
{en:'purpose', ko:'목적', pumsa:'NN'},
{en:'invalid', ko:'잘못된', pumsa:'JJ'},
{en:'defined', ko:'정의', pumsa:'VB'},
{en:'objects', ko:'객체', pumsa:'NNS'},
{en:'Classes', ko:'클래스', pumsa:'NNP'},
{en:'initial', ko:'초기', pumsa:'JJ'},
{en:'reading', ko:'읽기', pumsa:'NN'},
{en:'console', ko:'콘솔', pumsa:'NN'},
{en:'current', ko:'현재', pumsa:'JJ'},
{en:'message', ko:'메시지', pumsa:'NN'},
{en:'pointer', ko:'포인터', pumsa:'NN'},
{en:'modules', ko:'모듈', pumsa:'NNS'},
{en:'parsing', ko:'파싱', pumsa:'VBG'},
{en:'blocks', ko:'블록', pumsa:'NNS'},
{en:'google', ko:'구글', pumsa:'NN'},
{en:'thread', ko:'스레드', pumsa:'NN'},
{en:'errors', ko:'에러', pumsa:'NNS'},
{en:'system', ko:'시스템', pumsa:'NN'},
{en:'scopes', ko:'스코프', pumsa:'NNS'},
{en:'design', ko:'설계', pumsa:'NN'},
{en:'define', ko:'정의', pumsa:'VB'},
{en:'inputs', ko:'입력', pumsa:'NNS'},
{en:'aspect', ko:'측면', pumsa:'NN'},
{en:'purely', ko:'순수하게', pumsa:'RB'},
{en:'radius', ko:'반지름', pumsa:'NN'},
{en:'script', ko:'스크립트', pumsa:'NN'},
{en:'inside', ko:'안에서', pumsa:'JJ'},
{en:'static', ko:'정적', pumsa:'JJ'},
{en:'copies', ko:'사본', pumsa:'NNS'},
{en:'colors', ko:'색깔', pumsa:'NNS'},
{en:'always', ko:'항상', pumsa:'RB'},
{en:'second', ko:'두번째', pumsa:'JJ'},
{en:'second', ko:'두번째', pumsa:'JJ_noun'},
{en:'person', ko:'사람', pumsa:'NN'},
{en:'inside', ko:'내부', pumsa:'IN'},
{en:'change', ko:'변경', pumsa:'VB'},
{en:'change', ko:'변경', pumsa:'VBP'},
{en:'adding', ko:'추가', pumsa:'VBG'},
{en:'period', ko:'마침표', pumsa:'NN'},
{en:'invoke', ko:'호출', pumsa:'VBP'},
{en:'Martin', ko:'마틴', pumsa:'NNP'},
{en:'Robert', ko:'로버트', pumsa:'NNP'},
{en:'author', ko:'저자', pumsa:'NN'},
{en:'height', ko:'키', pumsa:'NN'},
{en:'letter', ko:'글자', pumsa:'NN'},
{en:'theory', ko:'이론', pumsa:'NN'},
{en:'prints', ko:'출력', pumsa:'VB'},
{en:'escape', ko:'이스케이프', pumsa:'VB'},
{en:'subset', ko:'부분집합', pumsa:'NN'},
{en:'header', ko:'헤더', pumsa:'NN'},
{en:'update', ko:'업데이트', pumsa:'VB'},
{en:'modify', ko:'수정', pumsa:'VB'},
{en:'Daniel', ko:'다니엘', pumsa:'NNP'},
{en:'jargon', ko:'전문 용어', pumsa:'NN'},
{en:'online', ko:'온라인', pumsa:'NN'},
{en:'nested', ko:'중첩된', pumsa:'VBN'},
{en:'nested', ko:'중첩', pumsa:'JJ'},
{en:'nested', ko:'중첩된', pumsa:'JJ_noun'},
{en:'pieces', ko:'조각', pumsa:'NNS'},
{en:'George', ko:'조지', pumsa:'NNP'},
{en:'folder', ko:'폴더', pumsa:'NN'},
{en:'random', ko:'무작위', pumsa:'JJ_noun'},
{en:'import', ko:'임포트', pumsa:'NN'},
{en:'import', ko:'임포트', pumsa:'VB'},
{en:'people', ko:'사람', pumsa:'NNS'},
{en:'Dorman', ko:'도먼', pumsa:'NNP'},
{en:'poetry', ko:'시', pumsa:'NN'},
{en:'shapes', ko:'도형', pumsa:'NNS'},
{en:'create', ko:'만드십시오', pumsa:'VB_imperative'},
{en:'hearts', ko:'하트', pumsa:'NNS'},
{en:'Linden', ko:'린덴', pumsa:'NNP'},
{en:'starts', ko:'시작', pumsa:'VB'},
{en:'Ubuntu', ko:'우분투', pumsa:'NNP'},
{en:'orange', ko:'오렌지', pumsa:'NN'},
{en:'suites', ko:'스위트', pumsa:'NNS'},
{en:'button', ko:'버튼', pumsa:'NN'},
{en:'called', ko:'호출', pumsa:'VB'},
{en:'passes', ko:'전달', pumsa:'VB'},
{en:'create', ko:'생성', pumsa:'VB'},
{en:'public', ko:'공용', pumsa:'JJ'},
{en:'passed', ko:'전달', pumsa:'VB'},
{en:'myelin', ko:'미엘린', pumsa:'NN'},
{en:'weight', ko:'무게', pumsa:'NN'},
{en:'parent', ko:'부모', pumsa:'NN'},
{en:'define', ko:'정의하고', pumsa:'VB_and'},
{en:'memory', ko:'메모리', pumsa:'NN'},
{en:'Python', ko:'파이썬', pumsa:'NNP'},
{en:'clause', ko:'절', pumsa:'NN'},
{en:'method', ko:'메서드', pumsa:'NN'},
{en:'module', ko:'모듈', pumsa:'NN'},
{en:'32-bit', ko:'32비트', pumsa:'JJ'},
{en:'custom', ko:'커스텀', pumsa:'NN'},
{en:'formal', ko:'정규', pumsa:'JJ'},
{en:'pickle', ko:'피클', pumsa:'NN'},
{en:'spaces', ko:'스페이스', pumsa:'NNS'},
{en:'output', ko:'출력', pumsa:'NN'},
{en:'syntax', ko:'문법', pumsa:'NN'},
{en:'common', ko:'공통', pumsa:'JJ'},
{en:'former', ko:'전자', pumsa:'JJ'},
{en:'caller', ko:'호출자', pumsa:'NN'},
{en:'escape', ko:'이스케이프', pumsa:'NN'},
{en:'8-bits', ko:'8비트', pumsa:'NNS'},
{en:'prefix', ko:'접두사', pumsa:'NN'},
{en:'itself', ko:'자신', pumsa:'PRP'},
{en:'primes', ko:'소수', pumsa:'NNS'},
{en:'digits', ko:'숫자', pumsa:'NNS'},
{en:'latter', ko:'후자', pumsa:'JJ'},
{en:'larger', ko:'더 큰', pumsa:'JJR'},
{en:'object', ko:'객체', pumsa:'NN'},
{en:'number', ko:'숫자', pumsa:'NN'},
{en:'floats', ko:'부동소수점 숫자', pumsa:'NNS'},
{en:'states', ko:'상태', pumsa:'NNS'},
{en:'binary', ko:'2진', pumsa:'JJ'},
{en:'string', ko:'문자열', pumsa:'NN'},
{en:'octals', ko:'8진수', pumsa:'NNS'},
{en:'arrays', ko:'배열', pumsa:'NNS'},
{en:'tuples', ko:'튜플', pumsa:'NNS'},
{en:'8-bits', ko:'8비트', pumsa:'JJ'},
{en:'really', ko:'정말', pumsa:'RB'},
{en:'simple', ko:'단순', pumsa:'JJ'},
{en:'object', ko:'객체', pumsa:'JJ'},
{en:'object', ko:'객체', pumsa:'VBP'},
{en:'slices', ko:'조각', pumsa:'NNS'},
{en:'sorted', ko:'정렬된', pumsa:'JJ'},
{en:'search', ko:'검색', pumsa:'NN'},
{en:'choice', ko:'선택', pumsa:'NN'},
{en:'values', ko:'값', pumsa:'NNS'},
{en:'useful', ko:'유용한', pumsa:'JJ_noun'},
{en:'define', ko:'정의', pumsa:'VBP'},
{en:'format', ko:'형태', pumsa:'NN'},
{en:'length', ko:'길이', pumsa:'NN'},
{en:'python', ko:'파이썬', pumsa:'NN'},
{en:'useful', ko:'유용', pumsa:'JJ'},
{en:'quotes', ko:'따옴표', pumsa:'NNS'},
{en:'Asimov', ko:'아시모프', pumsa:'NNP'},
{en:'inside', ko:'내부', pumsa:'NN'},
{en:'answer', ko:'답', pumsa:'NN'},
{en:'symbol', ko:'기호', pumsa:'NN'},
{en:'commas', ko:'콤마', pumsa:'NN'},
{en:'manage', ko:'관리', pumsa:'VB'},
{en:'result', ko:'결과', pumsa:'NN'},
{en:'tables', ko:'테이블', pumsa:'NNS'},
{en:'unique', ko:'유일한', pumsa:'JJ'},
{en:'return', ko:'반환', pumsa:'VBP'},
{en:'insert', ko:'삽입', pumsa:'VB'},
{en:'search', ko:'검색', pumsa:'VB'},
{en:'always', ko:'항상', pumsa:'RB_Clause'},
{en:'string', ko:'문자열', pumsa:'VBG'},
{en:'actual', ko:'실제', pumsa:'JJ'},
{en:'entire', ko:'전체', pumsa:'JJ'},
{en:'remove', ko:'제거', pumsa:'VB'},
{en:'return', ko:'반환', pumsa:'VB'},
{en:'colons', ko:'콜론', pumsa:'NNS'},
{en:'Google', ko:'구글', pumsa:'NNP'},
{en:'simple', ko:'단순한', pumsa:'JJ_noun'},
{en:'Peters', ko:'피터스', pumsa:'NNP'},
{en:'log in', ko:'로그인', pumsa:'VB'},
{en:'log in', ko:'로그인하고', pumsa:'VB_and'},
{en:'hyphen', ko:'하이픈', pumsa:'NN'},
{en:'branch', ko:'가지', pumsa:'NN'},
{en:'Amazon', ko:'아마존', pumsa:'NNP'},
{en:'recent', ko:'최근', pumsa:'JJ_noun'},
{en:'scroll', ko:'스크롤', pumsa:'VB'},
{en:'Alonzo', ko:'알론조', pumsa:'NNP'},
{en:'Church', ko:'처치', pumsa:'NNP'},
{en:'global', ko:'전역', pumsa:'JJ'},
{en:'global', ko:'전역', pumsa:'JJ_noun'},
{en:'Part I', ko:'1부', pumsa:'NN'},
{en:'Bjarne', ko:'비야네', pumsa:'NNP'},
{en:'greedy', ko:'적극적', pumsa:'RB_Clause'},
{en:'Sercan', ko:'세르칸', pumsa:'NNP'},
{en:'Leylek', ko:'라일레크', pumsa:'NNP'},
{en:'double', ko:'두', pumsa:'JJ_noun'},
{en:'GitHub', ko:'깃허브', pumsa:'NNP'},
{en:'option', ko:'옵션', pumsa:'NN'},
{en:'Thomas', ko:'토마스', pumsa:'NNP'},
{en:'client', ko:'클라이언트', pumsa:'NN'},
{en:'verify', ko:'확인', pumsa:'VB'},
{en:'select', ko:'선택', pumsa:'VB'},
{en:'server', ko:'서버', pumsa:'NN'},
{en:'gender', ko:'성별', pumsa:'NN'},
{en:'player', ko:'플레이어', pumsa:'NN'},
{en:'layout', ko:'레이아웃', pumsa:'NN'},
{en:'screen', ko:'화면', pumsa:'NN'},
{en:'corner', ko:'구석', pumsa:'NN'},
{en:'entire', ko:'전체', pumsa:'JJ_noun'},
{en:'exists', ko:'존재', pumsa:'VB'},
{en:'enter', ko:'입력', pumsa:'VB'},
{en:'exact', ko:'정확한', pumsa:'JJ_noun'},
{en:'match', ko:'일치', pumsa:'VB_imperative'},
{en:'match', ko:'일치', pumsa:'VB'},
{en:'third', ko:'세번째', pumsa:'JJ_noun'},
{en:'Flask', ko:'플라스크', pumsa:'NNP'},
{en:'cards', ko:'카드', pumsa:'NNS'},
{en:'check', ko:'체크', pumsa:'VB'},
{en:'click', ko:'클릭', pumsa:'VB'},
{en:'added', ko:'추가', pumsa:'VB'},
{en:'apple', ko:'사과', pumsa:'NN'},
{en:'match', ko:'일치하는 것', pumsa:'NN'},
{en:'cloud', ko:'클라우드', pumsa:'NN'},
{en:'small', ko:'작은', pumsa:'JJ_noun'},
{en:'reuse', ko:'재사용', pumsa:'NN'},
{en:'paths', ko:'경로', pumsa:'NNS'},
{en:'image', ko:'이미지', pumsa:'NN'},
{en:'flags', ko:'플래그', pumsa:'NNS'},
{en:'Style', ko:'스타일', pumsa:'NNP'},
{en:'guide', ko:'가이드', pumsa:'NN'},
{en:'rules', ko:'규칙', pumsa:'NNS'},
{en:'suite', ko:'스위트', pumsa:'NN'},
{en:'dices', ko:'주사위', pumsa:'NNS'},
{en:'stack', ko:'스택', pumsa:'NN'},
{en:'space', ko:'스페이스', pumsa:'NN'},
{en:'these', ko:'이들', pumsa:'DT'},
{en:'table', ko:'테이블', pumsa:'NN'},
{en:'union', ko:'합집합', pumsa:'NN'},
{en:'often', ko:'자주', pumsa:'RB'},
{en:'Excel', ko:'엑셀', pumsa:'NNP'},
{en:'saves', ko:'저장', pumsa:'VB'},
{en:'extra', ko:'추가적인', pumsa:'JJ_noun'},
{en:'tools', ko:'도구', pumsa:'NNS'},
{en:'still', ko:'여전히', pumsa:'RB'},
{en:'calls', ko:'호출', pumsa:'VBZ'},
{en:'UTF-8', ko:'UTF-8', pumsa:'NNP'},
{en:'error', ko:'에러', pumsa:'NN'},
{en:'three', ko:'세', pumsa:'CD'},
{en:'Isaac', ko:'아이작', pumsa:'NNP'},
{en:'catch', ko:'캐치', pumsa:'VB'},
{en:'alter', ko:'변경', pumsa:'VB'},
{en:'items', ko:'요소', pumsa:'NNS'},
{en:'books', ko:'책', pumsa:'NNS'},
{en:'words', ko:'단어', pumsa:'NNS'},
{en:'tests', ko:'테스트', pumsa:'NNS'},
{en:'below', ko:'다음', pumsa:'IN'},
{en:'great', ko:'훌륭한', pumsa:'JJ'},
{en:'named', ko:'이름 붙은', pumsa:'VBN'},
{en:'loops', ko:'루프', pumsa:'NNS'},
{en:'ASCII', ko:'ASCII', pumsa:'NNP'},
{en:'array', ko:'배열', pumsa:'NN'},
{en:'limit', ko:'한계', pumsa:'NN'},
{en:'range', ko:'범위', pumsa:'NN'},
{en:'usual', ko:'일반적인', pumsa:'JJ'},
{en:'basic', ko:'기본적인', pumsa:'JJ'},
{en:'octal', ko:'8진수', pumsa:'JJ'},
{en:'tuple', ko:'튜플', pumsa:'JJ'},
{en:'tuple', ko:'튜플', pumsa:'NN'},
{en:'comma', ko:'콤마', pumsa:'NN'},
{en:'above', ko:'위', pumsa:'IN'},
{en:'field', ko:'필드', pumsa:'NN'},
{en:'names', ko:'이름', pumsa:'NNS'},
{en:'NumPy', ko:'NumPy', pumsa:'NNP'},
{en:'index', ko:'인덱스', pumsa:'NN'},
{en:'forms', ko:'형태', pumsa:'NNS'},
{en:'local', ko:'지역', pumsa:'JJ'},
{en:'files', ko:'파일', pumsa:'NNS'},
{en:'order', ko:'순서', pumsa:'NN'},
{en:'every', ko:'모든', pumsa:'DT'},
{en:'store', ko:'저장', pumsa:'VB'},
{en:'Big-O', ko:'Big-O', pumsa:'NNP'},
{en:'valid', ko:'유효한', pumsa:'JJ'},
{en:'point', ko:'지점', pumsa:'NN'},
{en:'nodes', ko:'노드', pumsa:'NNS'},
{en:'given', ko:'주어진', pumsa:'VBN'},
{en:'bytes', ko:'바이트', pumsa:'NNS'},
{en:'types', ko:'타입', pumsa:'NNS'},
{en:'value', ko:'값', pumsa:'NN'},
{en:'float', ko:'부동소수점 숫자', pumsa:'NN'},
{en:'shape', ko:'도형', pumsa:'NN'},
{en:'child', ko:'자식', pumsa:'NN'},
{en:'model', ko:'모델화', pumsa:'VB'},
{en:'width', ko:'너비', pumsa:'NN'},
{en:'using', ko:'사용', pumsa:'VBG'},
{en:'terms', ko:'용어', pumsa:'NNS'},
{en:'start', ko:'시작', pumsa:'VB'},
{en:'Linux', ko:'리눅스', pumsa:'NNP'},
{en:'Peter', ko:'피터', pumsa:'NNP'},
{en:'owner', ko:'주인', pumsa:'NN'},
{en:'newly', ko:'새로', pumsa:'RB'},
{en:'cover', ko:'설명', pumsa:'VB'},
{en:'calls', ko:'호출', pumsa:'VB'},
{en:'issue', ko:'문제', pumsa:'NN'},
{en:'large', ko:'큰', pumsa:'JJ_noun'},
{en:'group', ko:'그룹', pumsa:'NN'},
{en:'Coyle', ko:'코일', pumsa:'NNP'},
{en:'stage', ko:'스테이지', pumsa:'NN'},
{en:'hints', ko:'힌트', pumsa:'NNS'},
{en:'slash', ko:'슬래시', pumsa:'NN'},
{en:'Woody', ko:'우디', pumsa:'NNP'},
{en:'Allen', ko:'앨런', pumsa:'NNP'},
{en:'quote', ko:'따옴표', pumsa:'NN'},
{en:'slice', ko:'슬라이스', pumsa:'VB'},
{en:'songs', ko:'노래', pumsa:'NNS'},
{en:'nouns', ko:'명사', pumsa:'NNS'},
{en:'found', ko:'발견', pumsa:'VB'},
{en:'color', ko:'색깔', pumsa:'NN'},
{en:'given', ko:'주어진', pumsa:'JJ_noun'},
{en:'print', ko:'출력', pumsa:'VB'},
{en:'steps', ko:'단계', pumsa:'NNS'},
{en:'Tools', ko:'도구', pumsa:'NNP'},
{en:'users', ko:'사용자', pumsa:'NNS'},
{en:'solve', ko:'해결', pumsa:'VB'},
{en:'James', ko:'제임스', pumsa:'NNP'},
{en:'reuse', ko:'재사용', pumsa:'VB'},
{en:'right', ko:'오른쪽', pumsa:'JJ'},
{en:'colon', ko:'콜론', pumsa:'NN'},
{en:'shell', ko:'셸', pumsa:'NN'},
{en:'lists', ko:'리스트', pumsa:'NNS'},
{en:'pipes', ko:'파이프', pumsa:'NNS'},
{en:'parts', ko:'부분', pumsa:'NNS'},
{en:'other', ko:'다른', pumsa:'JJ_noun'},
{en:'first', ko:'첫번째', pumsa:'JJ'},
{en:'first', ko:'첫번째', pumsa:'JJ_noun'},
{en:'empty', ko:'비어', pumsa:'JJ'},
{en:'empty', ko:'빈', pumsa:'JJ_noun'},
{en:'has-a', ko:'has-a', pumsa:'NN'},
{en:'scope', ko:'스코프', pumsa:'NN'},
{en:'input', ko:'입력', pumsa:'NN'},
{en:'state', ko:'상태', pumsa:'NN'},
{en:'Enter', ko:'엔터 키', pumsa:'NNP'},
{en:'calls', ko:'호출', pumsa:'NNS'},
{en:'style', ko:'스타일', pumsa:'NN'},
{en:'class', ko:'클래스', pumsa:'NN'},
{en:'block', ko:'블록', pumsa:'NN'},
{en:'call', ko:'호출', pumsa:'NN'},
{en:'real', ko:'진짜', pumsa:'JJ'},
{en:'open', ko:'열린', pumsa:'JJ'},
{en:'user', ko:'사용자', pumsa:'NN'},
{en:'most', ko:'대부분의', pumsa:'JJS'},
{en:'is-a', ko:'is-a', pumsa:'JJ'},
{en:'that', ko:'그', pumsa:'DT'},
{en:'core', ko:'핵심', pumsa:'NN'},
{en:'core', ko:'핵심', pumsa:'JJR'},
{en:'city', ko:'도시', pumsa:'NN'},
{en:'song', ko:'노래', pumsa:'NN'},
{en:'rule', ko:'규칙', pumsa:'NN'},
{en:'step', ko:'단계', pumsa:'NN'},
{en:'hint', ko:'힌트', pumsa:'NN'},
{en:'each', ko:'각', pumsa:'DT'},
{en:'pass', ko:'전달', pumsa:'VBP'},
{en:'left', ko:'왼쪽', pumsa:'JJ'},
{en:'Abby', ko:'애비', pumsa:'NNP'},
{en:'Cory', ko:'코리', pumsa:'NNP'},
{en:'four', ko:'네', pumsa:'CD'},
{en:'bash', ko:'배시', pumsa:'NN'},
{en:'Data', ko:'데이터', pumsa:'NNP'},
{en:'pipe', ko:'파이프', pumsa:'NN'},
{en:'verb', ko:'동사', pumsa:'NN'},
{en:'e.g.', ko:'예를 들어', pumsa:'FW'},
{en:'Mary', ko:'메리', pumsa:'NNP'},
{en:'Rose', ko:'로즈', pumsa:'NNP'},
{en:'Cook', ko:'쿡', pumsa:'NNP'},
{en:'mean', ko:'평균', pumsa:'NN'},
{en:'ways', ko:'방법', pumsa:'NNS'},
{en:'dogs', ko:'개', pumsa:'NNS'},
{en:'Ilya', ko:'일리야', pumsa:'NNP'},
{en:'card', ko:'카드', pumsa:'NN'},
{en:'deck', ko:'덱', pumsa:'NN'},
{en:'last', ko:'마지막', pumsa:'JJ'},
{en:'last', ko:'마지막', pumsa:'JJ_noun'},
{en:'Ward', ko:'워드', pumsa:'NNP'},
{en:'Unix', ko:'유닉스', pumsa:'NNP'},
{en:'Bash', ko:'배시', pumsa:'NNP'},
{en:'must', ko:'반드시', pumsa:'RB_Clause'},
{en:'need', ko:'필요', pumsa:'VB'},
{en:'same', ko:'같은', pumsa:'JJ_noun'},
{en:'type', ko:'타입', pumsa:'NN'},
{en:'save', ko:'저장', pumsa:'VB'},
{en:'Java', ko:'자바', pumsa:'NNP'},
{en:'very', ko:'매우', pumsa:'RB'},
{en:'data', ko:'데이터', pumsa:'NNS'},
{en:'name', ko:'이름', pumsa:'NN'},
{en:'dict', ko:'딕셔너리', pumsa:'NN'},
{en:'word', ko:'단어', pumsa:'NN'},
{en:'line', ko:'행', pumsa:'NN'},
{en:'next', ko:'다음', pumsa:'JJ'},
{en:'deep', ko:'깊은', pumsa:'JJ'},
{en:'call', ko:'호출', pumsa:'VB'},
{en:'list', ko:'리스트', pumsa:'NN'},
{en:'omit', ko:'생략', pumsa:'VB'},
{en:'form', ko:'형태', pumsa:'NN'},
{en:'less', ko:'덜', pumsa:'RBR'},
{en:'part', ko:'부분', pumsa:'NN'},
{en:'fear', ko:'공포', pumsa:'NN'},
{en:'this', ko:'이', pumsa:'DT'},
{en:'pair', ko:'쌍', pumsa:'NN'},
{en:'item', ko:'요소', pumsa:'NN'},
{en:'book', ko:'책', pumsa:'NN'},
{en:'copy', ko:'사본', pumsa:'NN'},
{en:'game', ko:'게임', pumsa:'NN'},
{en:'disk', ko:'디스크', pumsa:'NN'},
{en:'base', ko:'기수', pumsa:'NN'},
{en:'risk', ko:'위험', pumsa:'NN'},
{en:'more', ko:'더', pumsa:'RBR'},
{en:'much', ko:'훨씬', pumsa:'RB'},
{en:'code', ko:'코드', pumsa:'NN'},
{en:'byte', ko:'바이트', pumsa:'NN'},
{en:'case', ko:'경우', pumsa:'NN'},
{en:'loop', ko:'루프', pumsa:'NN'},
{en:'bits', ko:'비트', pumsa:'NNS'},
{en:'test', ko:'테스트', pumsa:'NN'},
{en:'next', ko:'다음', pumsa:'JJ_noun'},
{en:'i.e.', ko:'즉', pumsa:'FW'},
{en:'data', ko:'데이터', pumsa:'NN'},
{en:'same', ko:'같', pumsa:'JJ'},
{en:'call', ko:'호출', pumsa:'VBP'},
{en:'most', ko:'가장', pumsa:'RB'},
{en:'cell', ko:'셀', pumsa:'NN'},
{en:'sets', ko:'셋', pumsa:'NNS'},
{en:'time', ko:'시간', pumsa:'NN'},
{en:'hash', ko:'해시', pumsa:'NN'},
{en:'view', ko:'뷰', pumsa:'NN'},
{en:'keys', ko:'키', pumsa:'NNS'},
{en:'fast', ko:'빠른', pumsa:'JJ'},
{en:'sign', ko:'부호', pumsa:'NN'},
{en:'path', ko:'경로', pumsa:'NN'},
{en:'text', ko:'텍스트', pumsa:'NN'},
{en:'mode', ko:'모드', pumsa:'NN'},
{en:'file', ko:'파일', pumsa:'NN'},
{en:'tree', ko:'트리', pumsa:'NN'},
{en:'root', ko:'루트', pumsa:'NN'},
{en:'type', ko:'입력', pumsa:'VB'},
{en:'free', ko:'무료', pumsa:'JJ_noun'},
{en:'flag', ko:'플래그', pumsa:'NN'},
{en:'poem', ko:'시', pumsa:'NN'},
{en:'cost', ko:'비용', pumsa:'NN'},
{en:'adds', ko:'추가', pumsa:'VB'},
{en:'good', ko:'좋', pumsa:'JJ'},
{en:'good', ko:'좋은', pumsa:'JJ_noun'},
{en:'team', ko:'팀', pumsa:'NN'},
{en:'icon', ko:'아이콘', pumsa:'NN'},
{en:'Gale', ko:'게일', pumsa:'NNP'},
{en:'Ruby', ko:'루비', pumsa:'NNP'},
{en:'unit', ko:'단위', pumsa:'NN'},
{en:'uses', ko:'사용', pumsa:'VB'},
{en:'link', ko:'링크', pumsa:'NN'},
{en:'find', ko:'발견', pumsa:'VB'},
{en:'PyPI', ko:'PyPI', pumsa:'NNP'},
{en:'Olin', ko:'올린', pumsa:'NNP'},
{en:'menu', ko:'메뉴', pumsa:'NN'},
{en:'pass', ko:'전달', pumsa:'VB'},
{en:'GUI', ko:'GUI', pumsa:'NNP'},
{en:'top', ko:'맨 위', pumsa:'JJ'},
{en:'hit', ko:'클릭', pumsa:'VB'},
{en:'box', ko:'박스', pumsa:'NN'},
{en:'War', ko:'War', pumsa:'NNP'},
{en:'Git', ko:'깃', pumsa:'NNP'},
{en:'SVN', ko:'SVN', pumsa:'NNP'},
{en:'git', ko:'깃', pumsa:'NN'},
{en:'can', ko:'할 수', pumsa:'MD'},
{en:'Pip', ko:'pip', pumsa:'NNP'},
{en:'pip', ko:'pip', pumsa:'NN'},
{en:'web', ko:'웹', pumsa:'NN'},
{en:'any', ko:'어떤', pumsa:'DT'},
{en:'Tim', ko:'팀', pumsa:'NNP'},
{en:'Mac', ko:'맥', pumsa:'NNP'},
{en:'AWS', ko:'AWS', pumsa:'NNP'},
{en:'two', ko:'두', pumsa:'CD'},
{en:'way', ko:'방법', pumsa:'NN'},
{en:'bit', ko:'비트', pumsa:'NN'},
{en:'one', ko:'한', pumsa:'CD'},
{en:'key', ko:'키', pumsa:'NN'},
{en:'raw', ko:'가공되지 않은', pumsa:'JJ'},
{en:'CSV', ko:'CSV', pumsa:'NNP'},
{en:'row', ko:'행', pumsa:'NN'},
{en:'use', ko:'사용', pumsa:'VB'},
{en:'set', ko:'셋', pumsa:'NN'},
{en:'end', ko:'끝', pumsa:'NN'},
{en:'eye', ko:'눈', pumsa:'NN'},
{en:'use', ko:'사용하거나', pumsa:'VB_or'},
{en:'bag', ko:'가방', pumsa:'NN'},
{en:'ace', ko:'에이스', pumsa:'NN'},
{en:'Van', ko:'반', pumsa:'NNP'},
{en:'Der', ko:'데어', pumsa:'NNP'},
{en:'dog', ko:'개', pumsa:'NN'},
{en:'run', ko:'실행', pumsa:'VB'},
{en:'add', ko:'추가', pumsa:'VB'},
{en:'DJs', ko:'DJ', pumsa:'NNP'},
{en:'new', ko:'새', pumsa:'JJ'},
{en:'new', ko:'새', pumsa:'JJ_noun'},
{en:'OOP', ko:'OOP', pumsa:'NNP'},
{en:'bad', ko:'나쁜', pumsa:'JJ'},
{en:'C.', ko:'C.', pumsa:'NNP'},
{en:'C', ko:'C', pumsa:'NNP'},
];